### ISSUE TITLE
Some packages should be removed from "Release statuses" page

### ISSUE THREAD

**Issue by arogachev** [yiisoft-contrib/yiiframework.com#1009]
For example - docs, package template. Distorts stats a bit.

**Comment by arogachev** [comment]
Can be hard coded in a separate list and skipped - quick way.
Or some kind of mark in repository can be added and skipping will be done based on it - not so quick way.
Considering that repositories' names and quantity do not change so often and quantity of excluded repositories, hard code seems to be a decent option.

**Comment by vjik** [comment]
Is it possible to exclude packages by tag? We can add special tag for non-code packages.

**Comment by arogachev** [comment]
Good idea for "a mark", I'll try to research that.
