### ISSUE TITLE
Good Resource for Design

### ISSUE THREAD

**Issue by hscstudio** [yiisoft-contrib/yiiframework.com#102]
Hey all..

I always follow official site of Yii framework (http://yiiframework.domain-na.me/) day to day.. 
I think we should use outer for screenshoot of website image so it will look professional.. We can use it http://designscrazed.org/free-web-browser-mockups-psd/, 

I will update other good resource.. may be it help us.. I like Your job...

@jacmoe @cebe @samdark and @eshill

**Comment by samdark** [comment]
You mean fake browser window? Could be tried. I'm not sure if it would fit since it may clutter the page more. @eshill, what do you think?

**Comment by jacmoe** [comment]
If we had a dedicated 'powered by Yii' page, then perhaps.
Otherwise, I am not sure if we have any other content that could need it.

But a good resource - will probably use in some other project.

**Comment by samdark** [comment]
There's a plan to implement it but after initial launch. We're already abusing @jacmoe much w/ website development...

**Comment by hscstudio** [comment]
Haha... sorry @samdark
