### ISSUE TITLE
Broken links in "Understanding Yii3" wiki article

### ISSUE THREAD

**Issue by nkinash** [yiisoft-contrib/yiiframework.com#1028]
https://www.yiiframework.com/wiki/2547/draft-understanding-yii-3
It`s outdated, but search engine takes this link to top, when I search yii3

And here is the problem:
The article got wrong link to arabic site with broken certs and other - to uknown repository:
`Project source can be found at https://github.com/machour/yii3-kitchen-sink  Live web site: https://yii3.idk.tn/`

### What steps will reproduce the problem?

Just follow the link form the article

### What is the expected result?

Live website or project source

### What do you get instead?

Arabic site and uknown repository in github

**Comment by samdark** [comment]
Updated it to reflect current state of things.
