### ISSUE TITLE
Comments editor

### ISSUE THREAD

**Issue by jacmoe** [yiisoft-contrib/yiiframework.com#105]
The current comment system is not cutting it.

I am using Kartiks Markdown editor/processor and it is awesome.

http://demos.krajee.com/markdown-demo

The amount of work to apply it is minimal and people get preview and handy buttons.
And it supports Github-flavoured markdown as well.
Good for code snippets, etc.

Comments? :)

**Comment by jacmoe** [comment]
https://github.com/kartik-v/yii2-markdown

**Comment by samdark** [comment]
I have much better thing in draft. Gonna to release it soon so it can be used.

**Comment by jacmoe** [comment]
Great :+1: 
I wish that it can be hooked up with the Highlighter - the current code has dragons. ;)

**Comment by samdark** [comment]
Here's what I'm talking about: http://rmcreative.ru/playground/codemirror/

Try adding some code blocks for php and JavaScript to see highlighting and code completion in action.

**Comment by jacmoe** [comment]
Make the buttons focus the text area after insertion and it gets even better :+1: 
Keyboard short-cuts?

**Comment by samdark** [comment]
Done.

**Comment by samdark** [comment]
More suggestions?

**Comment by jacmoe** [comment]
Quote and mention (@..) - I think that would be it, actually, since it is going to be used for comments.
I don't think preview is needed.

**Comment by samdark** [comment]
Quote is there (need better icon for it). Do you expect mention to autocomplete people?

**Comment by jacmoe** [comment]
Yes, I'd expect that - although a mention without is better than no mention. ;)

**Comment by samdark** [comment]
Implemented completion for nicknames (there's a function to get a list). Invoked when typing `@` same as here at GitHub. Could be styled better.

**Comment by samdark** [comment]
@jacmoe more things that are good to have?

**Comment by cebe** [comment]
The default text "Write something great" is a bit confusing, just tried to edit or delete it until I found out it vanishes when I start to type :)

**Comment by cebe** [comment]
@samdark wow, I'm impressed. that thing looks really cool!

**Comment by cebe** [comment]
> there's a function to get a list

should be possible to load list while typing via ajax so it does not have to have all possible names.

**Comment by samdark** [comment]
@cebe it depends on where do we want to get names. If it's global then yes, we need AJAX. If it's only from previous comments we can gather these w/o additional request.

**Comment by jacmoe** [comment]
IMO, it makes no sense to allow mentions across topics, so I agree. It is not a forum or a Github, but a page specific comment section :)

**Comment by jacmoe** [comment]
> The default text "Write something great" is a bit confusing, just 
tried to edit or delete it until I found out it vanishes when I start to 
type :)

I think it will be much clearer when styling is applied. Placeholder 
text should be toned down so it is almost invisible but not quite.

**Comment by cebe** [comment]
> Placeholder text should be toned down so it is almost invisible but not quite.

:+1:

**Comment by samdark** [comment]
Yes. I'll do it.

**Comment by samdark** [comment]
About the code style and highlighting. Do we have agreement on how our code should look? If yes, please point to it, I'll style markdown code blocks to look exactly the same in the editor.

**Comment by cebe** [comment]
https://github.com/yiisoft-contrib/yiiframework.com/blob/master/scss/3-global/_highlight.scss

**Comment by jacmoe** [comment]
@cebe No - the code should be using the Github style - that highlight.scss is awful - and I don't think it is used anywhere except for the Yii 1.x guide?
It should be using the Highlight component IMO - I have hacked together an example in the comment component's view.
Currently the style is Github, but it can be changed easily to another theme.

**Comment by jacmoe** [comment]
~~~
<pre><code class="hljs php">
...
</code></pre>
~~~

**Comment by cebe** [comment]
Oh, sorry, should have read the comment "// Yii 1.1 guide code block highlights" :)

**Comment by jacmoe** [comment]
This is actually one situation where using the JS version of highlight is a good option because it will simply auto-highlight the code block that I posted in my previous comment - no extra processing is needed. No additional markup.

**Comment by samdark** [comment]
@jacmoe we want highlighting in PDF.

**Comment by jacmoe** [comment]
@samdark I copy that :+1:
I thought for a moment that the comments won't be available for off-line material.

**Comment by samdark** [comment]
They probably won't but code blocks are in the guide itself as well.

**Comment by jacmoe** [comment]
I am grabbing the contents of the code blocks and using the highlight component in the comments view file.
It works.
But it would be cleaner - and potentially safer - to use the js version for the comments - only the comments.

Both options only requires your edit component to produce this for code blocks:
~~~
<pre><code>
...
</code></pre>
~~~
Then either the js or the php highlight component can auto-highlight them as a post-processing step in the view.

**Comment by jacmoe** [comment]
If you do want to perform the highlight entirely manually then the style is in `vendor/scrivo/highlight.php/styles/github.css`

**Comment by ScottHuangZL** [comment]
I always like Kartiks widgets, well designed and well documented.

**Comment by hscstudio** [comment]
vote+1 kartik widgets http://demos.krajee.com/markdown-demo

**Comment by samdark** [comment]
@hscstudio have you seen my demo?

**Comment by hscstudio** [comment]
Yes,  http://rmcreative.ru/playground/codemirror/, very less feature for geek only :)

**Comment by samdark** [comment]
@hscstudio what's missing exactly?

**Comment by hscstudio** [comment]
1. Need guide for user, for example for link, we should show inputbox, so user can input url address
2. Need preview result
3. Need add icon :)

**Comment by jacmoe** [comment]
@hscstudio Are you absolutely sure?
A modal with basic Markdown syntax would be OK, but check out what we are using right now when commenting at Github: so minimal that the editor has disappeared.

**Comment by samdark** [comment]
1. These altert-boxes are huge obstacle for people familiar with markdown. Slowing you down greatly. Easy to implement though.
2. Could be implemented but I'm not sure it should. See https://github.com/yiisoft-contrib/yiiframework.com/issues/105#issuecomment-167645138
3. Yep, icons for buttons will be there, of course.

What kartik editor cons compared to what we have currently:

- Outdated markdown extra and SmartyPants used instead of GFM.
- No highlighting when editing.
- No code highlighting in code blocks.
- Bad for editing code. For example, you can't indent code block with TAB and SHIFT-TAB.
- No completion for lists.

**Comment by jacmoe** [comment]
I agree that this editor should not have popups - it is slow.
With the proper auto focus and perhaps even keyboard short-cuts, it could be really fast and stream-lined.
The Codemirror-based demo is really nice, with auto-completion etc, and I don't think that preview is needed. Because it is to  be used for short comments, not longer articles of text.

**Comment by jacmoe** [comment]
One quick request for improvement:
I like that it does auto-focus, but the focus should be *inside* of the tags when nothing has been selected - to save us from having to grapple for the arrow key :)

**Comment by samdark** [comment]
Yeah, that's something to adjust.

**Comment by rob006** [comment]
Comments on GitHub have a preview and it is really useful in some cases - I think it's a must-have feature.

**Comment by hscstudio** [comment]
Ok.. up to You...

if simple You should see github comment, but if no, You should see kartik markdown :)

**Comment by samdark** [comment]
Made some improvements. First of all, released suggestions and buttons toolbar as CodeMirror plugins distributed via bower packages:

- https://github.com/samdark/codemirror-autosuggest
- https://github.com/samdark/codemirror-buttons

As a result initialization code is simpler now.

Second, buttons behavior was improved to put cursor into useful position.

Check in action here: http://rmcreative.ru/playground/codemirror/

**Comment by jacmoe** [comment]
Perfect! :+1: 
I might even use this for another project of mine - if possible.

**Comment by samdark** [comment]
Yep, feel free to do so. Both are BSD-licensed.

**Comment by samdark** [comment]
Probably. Will try to attack it soon.
