### ISSUE TITLE
Please proactive gulp build for JS/CSS

### ISSUE THREAD

**Issue by ScottHuangZL** [yiisoft-contrib/yiiframework.com#106]
One proposal：
Please proactive build out all.min.js and all.min.css
Instead of asking each guy try to install npm, install gulp, and build, it is waste time.
In other word, except php/yii2 composer, the others please include into github already. Thanks.
Thanks

Regards,
Scott Huang

**Comment by ScottHuangZL** [comment]
The key issue is not easy to install gulp-sass which depend on node-sass which also need python2.7 (you cannot use python3.5*)
You see need a lot of tool chain...

So, please state the tool chain in your readme.md if possible, thanks.

**Comment by jacmoe** [comment]
We cannot do this because it is constantly generated and changes rapidly.
I am curious about how you managed to involve Python?
We have a guide to our build chain in our readme.
Apart from installing Node.js and Gulp globally, just run `npm install` at
the root folder.

**Comment by cebe** [comment]
@ScottHuangZL if you want to work on the site, you need the tools to re-build the css/js anyway. If you just want to take a look at the current state, see http://yiiframework.domain-na.me/

If you have concrete issues, feel free to post them and we'll try to help. On debian installing the toolchain went quite easy for me, what system are you on?

**Comment by jacmoe** [comment]
Once you managed to install it - by following our readme - then you can use that knowledge for other projects of yours.
Foundation is using Sass and Gulp and Bootstrap 4 is using Sass and Grunt, so I think getting used to the work-flow is useful, also in other projects.
So, as soon as you have worked out your problems, the better. ;)

**Comment by jacmoe** [comment]
If you are on Windows @ScottHuangZL then please read the readme as you might face a problem that has been solved already - check it out before you attempt to install again. :)

**Comment by ScottHuangZL** [comment]
Yeah, I am use Window.
I already compile JS/CSS by myself, not a problem, however, it will be challenge for newbies.
And npm speed is quite slow in China...
So I use mynpm.bat ( "npm --registry http://registry.cnpmjs.org %*") to install all related gulp-plugins
The gulp-sass will need node-sass and it request python2.x to install in advance for build.

**Comment by jacmoe** [comment]
That suggests that you are on an unsupported platform so you need to
compile.
Did you install the build tools as suggested in our readme?
But installing Python is easy.
If you use WinPython then it is easy to switch between 2.x and 3.x
I did that when I used Windows. I am not a Windows user anymore because of
Windows 10....

**Comment by jacmoe** [comment]
https://github.com/sass/node-sass/issues/1176

**Comment by ScottHuangZL** [comment]
Yeah, I am successfully install all, and the yiiframework.com run smoothly in my notebook already:)

And, how about add .htaccess file into the root folder and web folder? One example like below:
[htaccess.zip](https://github.com/yiisoft-contrib/yiiframework.com/files/74514/htaccess.zip)

**Comment by jacmoe** [comment]
The alternative to node-sass is to use Ruby sass and then you would have to
install Ruby and the sass gem...
So,even if node sass fails to fetch on a few systems it is better than
having to force everyone to get Ruby and Sass.

**Comment by ScottHuangZL** [comment]
haha, Python more popular than Ruby.  To be frankly, I try gulp-ruby-sass last night too, it can install, but emit some errors when try gulp build.   So, I use gulp-sass again at last, and it is work, just need remind guys to install Python2.5 ~ <3.0 in advance.

**Comment by jacmoe** [comment]
Great to hear that you got it sorted out :)
The goal for this project is not to attract newbies, BTW. :p
