### ISSUE TITLE
 A small bug in markup

### ISSUE THREAD

**Issue by unclead** [yiisoft-contrib/yiiframework.com#107]
I viewed current version of http://yiiframework.domain-na.me/ and found small bug on the page http://yiiframework.domain-na.me/doc/guide/2.0/en/intro-yii
http://prntscr.com/9n1mym

**Comment by SilverFire** [comment]
Confirmed, it looks as on the screenshot when the window width is between 1300 and 1650 px

**Comment by samdark** [comment]
Can't handle it since make fails for me locally so I have no guide / API :(

**Comment by jacmoe** [comment]
It is not a bug - it is a feature :+1: 

Since the scrollnav is outside of the grid, it can only be visible on large screens.
I can make it disappear at 1650px.
