### ISSUE TITLE
Move google code archives to own server

### ISSUE THREAD

**Issue by cebe** [yiisoft-contrib/yiiframework.com#109]
- what? https://code.google.com/p/yii/downloads/list?can=1&q=1.1
- why? https://code.google.com/p/support/wiki/ReadOnlyTransition

related to #6

**Comment by cebe** [comment]
put it into archive section in download page.

**Comment by samdark** [comment]
I don't think it should be at the website at all. We may create a special GitHub repo for the purpose and link to it.

**Comment by samdark** [comment]
~500mb in total.

**Comment by cebe** [comment]
https://github.com/yiisoft-contrib/museum

fixed by https://github.com/yiisoft-contrib/yiiframework.com/commit/d8f5278d9b9a46501bb50e40cdad7962e408d168#diff-0f858f726d4c53666103a90003e8d994R290
