### ISSUE TITLE
Get quotes from most well-known websites built with Yii

### ISSUE THREAD

**Issue by qiangxue** [yiisoft-contrib/yiiframework.com#11]
Please add more:
- vice.com and noisey.com
- humhub.org
- games.com (need to be verified)

**Comment by samdark** [comment]
Got quote from HumHub:

> The flexible Open Source Social Network Kit
> 
> Yii Framework is our rock solid foundation and provides us with numerous well designed features already out of the box.
> Especially the flexibility in form of modules or the event concept, perfectly match our requirements.
In and above that, Yii has very active and helpful community!
> 
> Lucas Bartholemy - CEO of HumHub

![humhub-teaser](https://cloud.githubusercontent.com/assets/47294/11534958/a5fc2838-9922-11e5-9a0b-ff5021e67485.jpg)

**Comment by bethrezen** [comment]
You can ask us for quote (devgroup.ru/dotplant.ru) 
But I need exact questions :)

**Comment by samdark** [comment]
Feel free to provide it. The question is "what Yii gives to your project, what's your favorite thing about Yii". Maximum 2 sentences.
