### ISSUE TITLE
Great if we add comment in docs/guide

### ISSUE THREAD

**Issue by hscstudio** [yiisoft-contrib/yiiframework.com#111]
Great if we add comment in doc/guide, but with follow rules for example http://php.net/manual/add-note.php, so yiier can post best practice about the topic. This comment should is moderate to filtering.

**Comment by samdark** [comment]
It's planned.

**Comment by samdark** [comment]
![comment_db](https://user-images.githubusercontent.com/47294/28570841-aa9102a6-7148-11e7-8a85-2a4d5509dd01.png)

**Comment by samdark** [comment]
Seems to be already done.
