### ISSUE TITLE
Security issue report update

### ISSUE THREAD

**Issue by retrymp3** [yiisoft-contrib/yiiframework.com#1112]
I had reported a security issue, according to your security policy (https://www.yiiframework.com/security) a couple of days back. Till now I haven’t gotten any response from there. Please let me know if there will be or are any updates. Thank you.
This is my email: achuthvpvp@gmail.com

**Comment by samdark** [comment]
Interesting. Either something went wrong or it went to spam or something. Please sent another email to my personal email, https://github.com/samdark

**Comment by retrymp3** [comment]
Hi, @samdark I had sent you an email yesterday addressing the security issue to [sam@rmcreative.ru] are there any updates regarding this. Thank you.

**Comment by samdark** [comment]
Yes. Got it. Thanks! Busy till the end of the week then will try to reproduce/fix it.

**Comment by retrymp3** [comment]
Any updates on the issue? I have submitted one more vulnerability.

**Comment by samdark** [comment]
No, I had no chance to look at it yet. Sorry.
