### ISSUE TITLE
Remove animation on page scrolling

### ISSUE THREAD

**Issue by samdark** [yiisoft-contrib/yiiframework.com#113]
Got complaints about it from community.

**Comment by jacmoe** [comment]
Fuck them! :-1: 

What animation?
The reveal on scroll (wow) on the front?

**Comment by samdark** [comment]
Yes. That animation.

**Comment by jacmoe** [comment]
Too bad. It added a nice touch to the front page IMO. The effect was subtle.
Oh, well.

And thanks for censoring my comment..

**Comment by samdark** [comment]
:+1:
