### ISSUE TITLE
Add Vagrant/Docker Box Official Yii

### ISSUE THREAD

**Issue by hscstudio** [yiisoft-contrib/yiiframework.com#119]
Sorry for disturb Your project :)

For next, good if we provide Vagrant/Docker box official Yii... so newbie can use it.. maybe it's same with Laravel with Homestead, it is simple but interested.. It's will make Yii look trendy @samdark, I know this is not about Yii, but about marketing Yii.

We dont close eyes, many Yiiers dont know about vagrant/docker :-1: 

We should more trendy from other, I love Yii

and then we can show again about benchmark of Yii. base on https://github.com/kenjis/php-framework-benchmark, we can select fullstack framework only.. and then we explain about it, and how to optimize or tune up.
For example
http://128.199.236.171/php-framework-benchmark/?php=5
http://128.199.236.171/php-framework-benchmark/

**Comment by SilverFire** [comment]
Duplicates https://github.com/yiisoft-contrib/yiiframework.com/issues/116

We already have a PR https://github.com/yiisoft/yii2-app-advanced/pull/105 with a Vagrant image. Feel free to join the discussion :)

Thank you for your adherence!

**Comment by hscstudio** [comment]
I think no duplicate.. this about box of vagrant /docker.. not about configuration

And this about benchmark.

**Comment by SilverFire** [comment]
Well, maybe I've misunderstood you, sorry.

Vagrant box is a pre-packed image, that can be easily assembled after https://github.com/yiisoft/yii2-app-advanced/pull/105 merge.

Currently we do not have any PR for the Docker. If you can help us - we will be really thankful.

Have I answered your questions?
