### ISSUE TITLE
Set up mailing list that people can subscribe for security issues

### ISSUE THREAD

**Issue by cebe** [yiisoft-contrib/yiiframework.com#12]
We discussed that before but did not do it yet.
http://www.yiiframework.com/forum/index.php/topic/55690-security-mailing-list/

related to #10

**Comment by machour** [comment]
I get a "sorry you don't have access to this link" when trying to visit that of forum link. Is it available somewhere else?

**Comment by samdark** [comment]
No but there aren't much details.

**Comment by samdark** [comment]
Not needed since GitHub advisories are now the thing.
