### ISSUE TITLE
get started session padding or magin

### ISSUE THREAD

**Issue by lukBarros** [yiisoft-contrib/yiiframework.com#121]
Man in the home, images slide pasted in borde bottom of the box. 10px ench. it spacing is buityfull.

**Comment by samdark** [comment]
Could you please elaborate?

**Comment by jacmoe** [comment]
If you are talking about adding padding to the slides for the front page, then that is not going to happen because of the design. ;)
I have already been told to remove padding for the bottom in order to satisfy @eshill - see #94

**Comment by lukBarros** [comment]
I speak precisely to improve the designer but all I understand.

**Comment by lukBarros** [comment]
Perhaps at least may have an edge on the bottom?

For images of white screens, it seems that breaks the backdrop of blue top (session) after the next session to be white leaves like a hole in the layout.
![captura de tela de 2016-02-14 22 19 31](https://cloud.githubusercontent.com/assets/1780909/13037884/0db511ee-d369-11e5-9133-3080315b6d4a.png)
![captura de tela de 2016-02-14 22 19 28](https://cloud.githubusercontent.com/assets/1780909/13037885/0dd36374-d369-11e5-9653-ecb47afcd8d9.png)

**Comment by lukBarros** [comment]
@samdark think about it?

**Comment by samdark** [comment]
I'm not sure what do you propose exactly.

**Comment by jacmoe** [comment]
We have discussed this before. And the answer is no.
See the issue I linked to earlier.
