### ISSUE TITLE
page team layout is bad

### ISSUE THREAD

**Issue by lukBarros** [yiisoft-contrib/yiiframework.com#122]
Mans in http://yiiframework.domain-na.me/team the description of Maurizio Domba crash alling of boxers... its no biutfyull for look.

**Comment by samdark** [comment]
It's gonna be restyled soon: https://github.com/eshill/yiiframework.com/blob/master/png/team.png

**Comment by lukBarros** [comment]
That's better, I feel proud to be one of the faces shown as contributors.
