### ISSUE TITLE
Translater site

### ISSUE THREAD

**Issue by lukBarros** [yiisoft-contrib/yiiframework.com#124]
Translater terms of site? Who?

**Comment by cebe** [comment]
current plans will have site in english only but we may add i18n support later. Too much for the first start though.

-

**Comment by lukBarros** [comment]
You could already pass all strings inside the internationalization method , would be a departure, as to leave at least the implementation i18n made ​​by simply writing leaves translation of additional languages.

**Comment by lukBarros** [comment]
@cebe ?

**Comment by jacmoe** [comment]
@lukBarros Yes, but later :)

@cebe said:

> Too much for the first start

We are looking forward to your contributions after the launch :+1:

**Comment by lukBarros** [comment]
Ok @jacmoe let's rock!

**Comment by jacmoe** [comment]
Don't worry @lukBarros - you'll be back :+1:

**Comment by LAV45** [comment]
### Can help with translation of contents
Demo site: https://yii2-translated-behavior.herokuapp.com/
Source code: https://github.com/LAV45/yii2-translated-behavior-demo

**Comment by samdark** [comment]
It's launched now but I'm not sure it's a good idea to have website translated...
