### ISSUE TITLE
Provide PDF and CHM docs

### ISSUE THREAD

**Issue by samdark** [yiisoft-contrib/yiiframework.com#13]
These are really important and we should automatically build these from sources and provide a way to download these right from website.

**Comment by samdark** [comment]
https://github.com/blacksmoke26/yii2-manual-chm/

**Comment by arogachev** [comment]
After discussion with @samdark we decided to not add CHM. See this comment for details (related) - https://github.com/yiisoft/yii2-apidoc/issues/47#issuecomment-982374448.

And HTML with PDF are already available.

**Comment by arogachev** [comment]
@iJackUA Thanks for suggesting ePub, I moved it to https://github.com/yiisoft/yii2-apidoc/issues/270.
