### ISSUE TITLE
I can not access the `guide`

### ISSUE THREAD

**Issue by vishuB** [yiisoft-contrib/yiiframework.com#140]
hi @cebe,

 Please help me

First i install new `yiiframework.com` Website

and generate document using `make docs` command

now i access the `guide` in website then get `Not Found` Error.
url is `http://localhost/yiiframework.com/web/doc/guide/2.0/en`

![screenshot-localhost 2016-07-25 12-21-31](https://cloud.githubusercontent.com/assets/13677102/17095018/2440659a-5270-11e6-83cd-56c29d6f2326.png)

**Comment by samdark** [comment]
Has `make docs` succeeded?

**Comment by vishu-46** [comment]
Thanl's @samdark for reply

yes,
but, elasticsearch error. show below image

![screenshot- domain date time](https://cloud.githubusercontent.com/assets/13677102/17102389/f814dc18-5296-11e6-99fd-2be4d2aef41f.png)

**Comment by samdark** [comment]
It seems when it's unable to write ES index it stops so you have docs generated only for API.

**Comment by samdark** [comment]
Solution is either to install ElasticSearch or to introduce a parameter that allows skipping index.

**Comment by vishu-46** [comment]
i have already install ElasticSearch

**Comment by samdark** [comment]
Then adjust config to use it.

**Comment by vishu-46** [comment]
how to config ?

**Comment by samdark** [comment]
https://github.com/yiisoft-contrib/yiiframework.com/blob/master/config/params.php#L26

**Comment by cebe** [comment]
elasticsearch failure will not stop generating the docs, there must be something else missing.

**Comment by vishu-46** [comment]
@cebe what missing?

**Comment by cebe** [comment]
yeah, that is because yii is not able to connect to elasticsearch. that should not affect the guide generation in general though, but only the search part. the guide itself should work as you see "Finished guide 2.0 in English." below the error.

**Comment by vishu-46** [comment]
why i can not access the `guide`.

url is http://localhost/yiiframework.com/web/doc/guide/2.0/en

![guide_img](https://cloud.githubusercontent.com/assets/13677102/17290596/e3ee828c-57fc-11e6-897b-e080383e76c7.png)

**Comment by blakeyman** [comment]
http://www.yiiframework.com/doc-2.0/guide-index.html

wrong URL

**Comment by vishu-46** [comment]
Please access the new [yiiframework.com](http://www.yiiframework.com/doc-2.0/guide-index.html) website `guide`.

**Comment by samdark** [comment]
@vishu-46 ?
