### ISSUE TITLE
Generate PDF for Japanese and Chinese Guide

### ISSUE THREAD

**Issue by cebe** [yiisoft-contrib/yiiframework.com#142]
turns out it is not so easy to generate PDF from japanese and chinese guide.

https://en.wikibooks.org/wiki/LaTeX/Internationalization#Chinese
https://en.wikibooks.org/wiki/LaTeX/Internationalization#Japanese

If someone wants to try an implementation, add an entry for the language [here](https://github.com/yiisoft-contrib/yiiframework.com/blob/659fb6fdbcdd1b787ef8ff45efd74e8a78ce2376/config/params.php#L86-L96). And adjust the code that changes the main.tex file for language support in [GuideController command](https://github.com/yiisoft-contrib/yiiframework.com/blob/659fb6fdbcdd1b787ef8ff45efd74e8a78ce2376/commands/GuideController.php#L82).
I'm happy to help if anything else is unclear.

**Comment by cebe** [comment]
https://github.com/samdark/yii2-cookbook/issues/176

**Comment by cebe** [comment]
https://github.com/samdark/yii2-cookbook/issues/176#issuecomment-412907545

**Comment by cuileon** [comment]
I have generated a Chinese document and the code should look like this:
```
// https://en.wikibooks.org/wiki/LaTeX/Internationalization#Chinese
// TODO this does not work yet. See https://github.com/yiisoft-contrib/yiiframework.com/issues/142
file_put_contents("$pdfTarget/main.tex", str_replace(['\usepackage[british]{babel}', '\begin{document}', '\end{document}'], ['\usepackage{CJKutf8}', '\begin{document}' . PHP_EOL . '\begin{CJK}{UTF8}{gbsn}', '\end{CJK}' . PHP_EOL . '\end{document}'], file_get_contents("$pdfTarget/main.tex")));
```

**Comment by cuileon** [comment]
The premise is that you need to install Chinese fonts, `{gbsn}` is the name of the Chinese font called: "宋体"

**Comment by cebe** [comment]
Nice! Thanks for figuring this out! Will deploy this to the website soon.

**Comment by cebe** [comment]
I had to make some fixes in the guide to make the PDF compile @cuileon FYI: https://github.com/yiisoft/yii2/commit/f79d3d7edc90963d4de61d6f8e7fa5d76680ff20

**Comment by cebe** [comment]
Turns out the same thing also works for Japanese Guide :)

**Comment by cebe** [comment]
@softark FYI, Japanese Guide is now also available as PDF.

btw, if you add a `translators.json` file, your names will be listed in the PDF as translation authors:

https://github.com/yiisoft/yii2/blob/d07e286dbdc2d5990942bb71ee49698a0051091d/docs/guide-ru/translators.json

**Comment by softark** [comment]
Thanks, @cebe  and @cuileon !!
I didn't know it at all.

**Comment by softark** [comment]
Well, some characters become blank in Japanese PDF.

The most critical character missing in PDF is "的", which is frequently used in the guide, e.g. "汎用的" (generic), "進化的" (evolutionary), ... etc. It's a suffix to convert a noun into an adjective which is very frequently used in Japanese (and also in Chinese, I think). 

![image](https://user-images.githubusercontent.com/342857/49870546-0a1bbd00-fe57-11e8-8735-77b7043b9989.png)

A strange thing is that it occurs when you open the PDF in Chrome browser while it doesn't in Adobe Reader.

![image](https://user-images.githubusercontent.com/342857/49870673-6ed71780-fe57-11e8-9676-dff5416ea930.png)

I don't know why.

Maybe we'll be able to forget this small flaw ... but would you please try a different font `ipxm` in place of `min` ? Some Japanese documents on LaTeX says that you should use `ipxm` and `ipxg` in place of `min` and `goth`. Sorry, if I had an testing environment I could have tested it myself, but I can't at the moment.

**Comment by cebe** [comment]
> Some Japanese documents on LaTeX says that you should use `ipxm` and `ipxg` in place of `min` and `goth`. Sorry, if I had an testing environment I could have tested it myself, but I can't at the moment.

No problem, I can test this.

I made two versions of PDF, one with ipxm and one with ipxg:

- [guide_ipxm.pdf](https://github.com/yiisoft-contrib/yiiframework.com/files/2674991/guide_ipxm.pdf)
- [guide_ipxg.pdf](https://github.com/yiisoft-contrib/yiiframework.com/files/2674997/guide_ipxg.pdf)

@softark Please download and let me know which one is better.

**Comment by cuileon** [comment]
@softark @cebe I have checked the Chinese guide and the fonts are perfect.

[guide-zh-cn](https://www.yiiframework.com/doc/download/yii-guide-2.0-zh-cn.pdf)

**Comment by softark** [comment]
Thank you @cebe. The both of them are OK. They both render perfectly. 
But we should use `ipxm`, because serif fonts (`min` and `ipxm`) are preferred more than sans-serif fonts (`goth` and `ipxg`) in printed books. The former is easier to read.

**Comment by softark** [comment]
And I will add `translators.json` to the Japanese guide. I think I have the right to be proud of myself being in this great community.

**Comment by softark** [comment]
Just made a PR #417

**Comment by samdark** [comment]
Merged. @cebe would you please deploy it and trigger re-rendering?

**Comment by cebe** [comment]
done.

**Comment by samdark** [comment]
@softark is it good now?

**Comment by softark** [comment]
Yes, it's perfect now.
