### ISSUE TITLE
Login and signup pages

### ISSUE THREAD

**Issue by cebe** [yiisoft-contrib/yiiframework.com#144]
This is an extract from the monster Mock issue.

- https://github.com/yiisoft-contrib/yiiframework.com/issues/94#issuecomment-170560990
- https://github.com/yiisoft-contrib/yiiframework.com/issues/94#issuecomment-218370946

**Comment by johonunu** [comment]
@cebe I have already coded these, it's already merged ;)
https://github.com/yiisoft-contrib/yiiframework.com/pull/110

**Comment by cebe** [comment]
Yeah right, had not seen them, thanks :)
