### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by cebe** [yiisoft-contrib/yiiframework.com#145]
This is an extract from the monster Mock issue.

here is a wiki mock: https://github.com/yiisoft-contrib/yiiframework.com/issues/94#issuecomment-197351598
- [x] implement design
- [x] create db layout
- [x] create model layer
- [x] implement controller actions
- [ ] import data from old site

**Comment by johonunu** [comment]
@cebe I will work on coding the wiki design this week. Will create pull request when done.

**Comment by cebe** [comment]
cool, thanks.
