### ISSUE TITLE
Port extensions from old website

### ISSUE THREAD

**Issue by samdark** [yiisoft-contrib/yiiframework.com#15]
- Use the same data.
- Use the same URLs.

**Comment by cebe** [comment]
https://github.com/yiisoft/yii2/issues/2395

**Comment by cebe** [comment]
- [ ] implement star/bookmark #166 
- [ ] implement rating #167

**Comment by cebe** [comment]
related: https://github.com/yiisoft-contrib/yiiframework.com/issues/19
