### ISSUE TITLE
Need design/styling for User pages

### ISSUE THREAD

**Issue by cebe** [yiisoft-contrib/yiiframework.com#155]
As of #36 the old user system will be ported to the new site as is, meaning we have the following functionality which needs some styling:
- [x] User List: http://www.yiiframework.com/user/
- [x] User Public Profile page: http://www.yiiframework.com/user/2/
- [x] Hall Of Fame http://www.yiiframework.com/user/halloffame/
- [x] Badges http://www.yiiframework.com/badges/
- [x] Badge Detail Page http://www.yiiframework.com/badge/supporter/

**Comment by samdark** [comment]
Overall it's cleaned up and, at least, doesn't looks bad.
