### ISSUE TITLE
Guide Header Menu

### ISSUE THREAD

**Issue by agungsijawir** [yiisoft-contrib/yiiframework.com#159]
Current situation, Menu Selection on Guide & API Doc looks weird.

**Guide Menu**
![screen shot 2016-08-27 at 3 28 15 am](https://cloud.githubusercontent.com/assets/1901132/18019448/5e2e8b24-6c06-11e6-95dd-01da6654f276.png)

**API Documentation Menu**
![screen shot 2016-08-27 at 3 28 25 am](https://cloud.githubusercontent.com/assets/1901132/18019462/704abf1c-6c06-11e6-8894-b4211a3f0f5e.png)

---

Propose Fix,

**Guide Menu**
![screen shot 2016-08-27 at 3 29 38 am](https://cloud.githubusercontent.com/assets/1901132/18019485/884d66e6-6c06-11e6-97d4-2ce0b1f3ea1d.png)

**API Documentation Menu**
![screen shot 2016-08-27 at 3 29 31 am](https://cloud.githubusercontent.com/assets/1901132/18019497/92994aa2-6c06-11e6-941f-01eba4529f85.png)

**On Mobile Resolution (768px)**
![screen shot 2016-08-27 at 3 00 08 am](https://cloud.githubusercontent.com/assets/1901132/18019512/a317122e-6c06-11e6-98fa-31e3bcdf41db.png)

![screen shot 2016-08-27 at 3 00 29 am](https://cloud.githubusercontent.com/assets/1901132/18019520/a9a547e6-6c06-11e6-8c78-61b6a744a4d0.png)

![screen shot 2016-08-27 at 3 33 55 am](https://cloud.githubusercontent.com/assets/1901132/18019608/20349de4-6c07-11e6-8da4-ff707fa748e4.png)

**Comment by cebe** [comment]
fixed, thanks for reporting!
