### ISSUE TITLE
finish user badge and user ranking

### ISSUE THREAD

**Issue by cebe** [yiisoft-contrib/yiiframework.com#164]
follow up to #156 
- [ ] badges:
  - [x] afterLogin: add user to badge queue
  - [x] finish and test badge console command
  - [x] finish implementation of badge models
  - [ ] implement something to have forum badges working
- [x] member rating cronjob (depends on Extensions and wiki)

**Comment by Deele** [comment]
I am suggesting to make badges more valuable - integrate with [openbadges.org](https://openbadges.org/) so that users can brag about them in standardized way. That would bring a bit more incentive to earn them.

**Comment by samdark** [comment]
@Deele could be done after release.

**Comment by cebe** [comment]
the rest is done.
