### ISSUE TITLE
Implement +1 / -1 rating for comments, wiki and extensions

### ISSUE THREAD

**Issue by cebe** [yiisoft-contrib/yiiframework.com#167]
- [x] add model and table
- [x] add rating button and controller actions
- [x] add to comments
- [x] add to wiki
- [x] add to extensions (#15)
- [x] import data from old site

**Comment by cebe** [comment]
current UI does not show whether current user has cased a vote or not. Should be possible to withdraw a vote.

**Comment by samdark** [comment]
Extensions seems to have rating already...

**Comment by cebe** [comment]
rating is basically ready, the problem is that the current styling gives no feedback over whether you have rated something or not. Also you can not take back the rating once done, so if you clicked "up" you can only change it to "down", but never remove the rating completely.

**Comment by samdark** [comment]
Then it's not critical for launch.
