### ISSUE TITLE
After signup user can already do everything

### ISSUE THREAD

**Issue by cebe** [yiisoft-contrib/yiiframework.com#169]
This should be limited until email is validated to prevent spam.
Also other methods should be applied to prevent spam account creation.

- [x] prevent editing of non-owned wiki pages until enough carma has been gathered. 
- [x] prevent creation of wiki pages until account is verified (email is validated or user is from github).
- [x] prevent creation of new extension until account is validated.
- [x] there is some limitation on forum posts, need to figure out how that is configured right now.
- [x] implement user email validation #222

**Comment by samdark** [comment]
Forum posts rule is the following:

> Allow users who have at least 1 post and registered 3 days ago

**Comment by samdark** [comment]
I'm not sure we need it anymore. "Enough karma" is better criteria.

**Comment by samdark** [comment]
@cebe do we have email validation implemented?

**Comment by cebe** [comment]
If you mean validation of email by clicking a link in the mail, then no.

**Comment by samdark** [comment]
Did you mean that by the following?

> This should be limited until email is validated to prevent spam.

**Comment by cebe** [comment]
yes

**Comment by samdark** [comment]
https://github.com/yiisoft-contrib/yiiframework.com/commit/eb577865ba4a73d23d4d722c64edb1910a8e1244
