### ISSUE TITLE
how to install guide and apidoc and the results of your site as a thank you!

### ISSUE THREAD

**Issue by havoes** [yiisoft-contrib/yiiframework.com#170]
I would like to ask, how to install guide and apidoc and the results of your site as a thank you!
I come from http://www.yiiok.com

**Comment by samdark** [comment]
Use console commands to fetch/generate docs.

**Comment by cebe** [comment]
@havoes current state of development is hosted at http://yiiframework.domain-na.me/ btw.

**Comment by havoes** [comment]
Thanks!
