### ISSUE TITLE
Outdated download page

### ISSUE THREAD

**Issue by mdziczkowski** [yiisoft-contrib/yiiframework.com#175]
Hey. I wanted to let you know that the informations given on the download page are quite outdated and not actual. Please urgently fix them. Thanks

**Comment by cebe** [comment]
Are you talking about http://www.yiiframework.com/download/ or http://www.yiiframework.domain-na.me/download ?

**Comment by mdziczkowski** [comment]
the first one. I didn't even know that a alternative page (the second one you gave) even exist

**Comment by cebe** [comment]
what is wrong with the first one?

> The latest version of Yii 2 is 2.0.10, released on October 20, 2016.

that is the latest release.

**Comment by mdziczkowski** [comment]
@cebe it contains the old version of files with are required and downloaded thru composer

**Comment by cebe** [comment]
@mdziczkowski I have just double checked all the links on that page, please state exactly what is wrong. What do you download or what do you do? what do you see? what did you expect to be different?

**Comment by mdziczkowski** [comment]
the problem isn't the website itself but the part releated to composer. For example, there are newer versions of fxp/composer-asset-plugin and the downloaded for it components.

I think that there should be a alternative for it avaliable for the framework avaliable with don't need use of the buggy composer

**Comment by cebe** [comment]
> For example, there are newer versions of fxp/composer-asset-plugin and the downloaded for it components.

I have updated the version constraint for the `fxp/composer-asset-plugin`.

> I think that there should be a alternative for the framework to be able to be used without the need use of the buggy composer

You can download the archive file instead of using the composer commands.

**Comment by jacmoe** [comment]
I am not sure where to put this, but I wonder why Yii is using the composer asset plugin at all, especially considering that it is buggy and much slower than just running Bower/npm - 90 % of all Composer related issues is because of the asset plugin. :)

**Comment by mdziczkowski** [comment]
I agree wuth @jacmoe. Composer is too buggy to use it at all

@cebe 

> You can download the archive file instead of using the composer commands.
it seem that to initialize or create a project in yii, the composer need to be used :(

**Comment by jacmoe** [comment]
I love Composer :)
It has made it easy to use a lot of libraries together - and these days I
tend to use Composer ready libraries directly instead of relying on Yii
extensions.

I hate the asset plug in though.
In my own projects I use Bower and npm directly because it is 10 times (at
least) faster.

**Comment by cebe** [comment]
this topic has been widely discussed at https://github.com/yiisoft/yii2/issues/8688, the plugin will be optional in 2.1.

**Comment by jacmoe** [comment]
Thanks Carsten - sounds great!

Den 21/11/2016 21.04 skrev "Carsten Brandt" <notifications@github.com>:

**Comment by jacmoe** [comment]
Michal - you don't have to use the project generator to start a Yii
project.
But you need to use Composer.
Get used to it because it is used in all modern PHP projects these days.

The project generator is convenient but you can just require Yii manually.
