### ISSUE TITLE
Current website feedback

### ISSUE THREAD

**Issue by samdark** [yiisoft-contrib/yiiframework.com#184]
http://www.yiiframework.com/forum/index.php/topic/73490-yii-website-is-out-of-date/

**Comment by menapro** [comment]
Is theme design currently closed?

**Comment by samdark** [comment]
No, current design isn't set in stone, of course. If something really stunning will be proposed, we're OK switching to it.

**Comment by cebe** [comment]
we also need to improve design for wiki and extension pages + some user content pages, which is not really finished.

**Comment by allyraza** [comment]
@menapro if you have some ideas please do bring them forward

**Comment by samdark** [comment]
Closing since it's a meta-issue.
