### ISSUE TITLE
Make a showcase of things built with yii

### ISSUE THREAD

**Issue by cebe** [yiisoft-contrib/yiiframework.com#185]
**Open Source:**

- https://github.com/LimeSurvey/LimeSurvey
- https://www.humhub.org/en
- http://phundament.com/
- ...

**Yii based CMS:**

- https://github.com/samdark/awesome-yii#cms-and-engines-yii2-based

**Websites:**

- https://www.stay.com/
- ...

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/projects/4

**Comment by samdark** [comment]
I have a yiipowered.com domain and planned to implement a simple community-powered multi-language showcase website there so instead of integrating it into yiiframework.com, separate website could expose data via REST API. Accounts could be linked via github profile IDs and emails.

**Comment by samdark** [comment]
May make more sense since lots of websites aren't in English and aren't likely to be described in English. It is relatively easy to support multiple languages for such narrow scope but hard for the whole website.

**Comment by samdark** [comment]
From the other hand, it is tempting to have it as part of the website.

**Comment by samdark** [comment]
![showcase_entities](https://cloud.githubusercontent.com/assets/47294/22151600/c57244c8-df2f-11e6-87fe-fa72d7cdb93d.png)

**Comment by samdark** [comment]
Decided to make it a separate project.

**Comment by samdark** [comment]
http://yiipowered.com/en/

**Comment by samdark** [comment]
Need to add a link to website menus.

**Comment by samdark** [comment]
Here's an API which could be used to bring a list of projects to the front page: http://yiipowered.com/en/api/1.0
