### ISSUE TITLE
Implement Background processing

### ISSUE THREAD

**Issue by cebe** [yiisoft-contrib/yiiframework.com#189]
- emails
- extension data update from packagist
- update of user rankings
- ....

some resources:

- https://github.com/chrisboulton/php-resque
- ...

**Comment by samdark** [comment]
I think it's better to use https://github.com/zhuravljov/yii2-queue. The plan is to adopt it under yiisoft anyway...

**Comment by cebe** [comment]
using yii2-queue now.
