### ISSUE TITLE
New book and videos from Packt

### ISSUE THREAD

**Issue by packtpartner** [yiisoft-contrib/yiiframework.com#190]
Hi,

We have our books and videos featured on http://www.yiiframework.com/
Packt has published 3 new titles recently.
[Yii2 Application Development Cookbook - Third Edition](https://www.packtpub.com/web-development/yii2-application-development-cookbook-third-edition)
[Yii2 Application Development Solutions - Volume 1 (Video)](https://www.packtpub.com/web-development/yii2-application-development-solutions-volume-1)
[Yii2 Application Development Solutions - Volume 2 (Video)](https://www.packtpub.com/application-development/yii2-application-development-solutions%E2%80%93volume-2-video)

We have been in touch with Qiang Xue to feature our titles on the website, but haven't heard back from him in a while.
We would appreciate if someone from the team could help us out with this.

Thanks and regards.

**Comment by samdark** [comment]
We'll list these a new website. Thanks.

**Comment by packtpartner** [comment]
Can you please share the link of the website once these titles are featured @samdark ?

**Comment by samdark** [comment]
Sure.

**Comment by packtpartner** [comment]
Any idea when can this be done @samdark ?

**Comment by cebe** [comment]
The site will be published when its ready. We have no time frame for that right now.

**Comment by samdark** [comment]
Book should definitely be featured. Not sure about videos since these seems to be of a bad quality based on public user feedback.
