### ISSUE TITLE
Wiki: revision notice on articles with only one revision

### ISSUE THREAD

**Issue by samdark** [yiisoft-contrib/yiiframework.com#195]
![single_revision](https://user-images.githubusercontent.com/47294/28757447-1dd147e8-758c-11e7-9420-e5ef29e68be7.png)

Notice should be hidden in case there's a single revision.

**Comment by cebe** [comment]
this shows up if you link directly to the revision, e.g.

`/wiki/849/test?revision=1`, not if you link to `/wiki/849/test`, this is expected.

**Comment by cebe** [comment]
okay, `You may want to see the changes made in this revision.` should be hidden on first revision, as there are no changes.
