### ISSUE TITLE
Auth with Github don't work

### ISSUE THREAD

**Issue by diezztsk** [yiisoft-contrib/yiiframework.com#198]
How to repeat:
1. Click Top menu -> Extensions
2. Click Create new Extension
3. Click Login with Github
4. After success login with Github I see blank page with next text:
```
Array ( [display_name] => Array ( [0] => Display Name cannot be blank. ) )
```

**Comment by Insolita** [comment]
+1

**Comment by jacmoe** [comment]
@Insolita Use the "reaction" button instead of a pretty much useless plus one comment.
That is the reason why Github Reactions were added! 😄

**Comment by hirenbhut93** [comment]
still is not working in live demo.

**Comment by cebe** [comment]
fix has been deployed.
