### ISSUE TITLE
Inspiration from other framework sites

### ISSUE THREAD

**Issue by cebe** [yiisoft-contrib/yiiframework.com#20]
- http://phalconphp.com/en/
- http://www.codeigniter.com/
- http://www.slimframework.com/
- http://cakephp.org/
- http://symfony.com/
- http://laravel.com/

**Comment by jacmoe** [comment]
Could one of you guys make a screen shot like that and post it here ?

I haven't got PHPStorm, and I think it should be made using that considering that they are sponsoring the project..

I could make a parallax header thing for a section of the site - maybe the wiki section? (snippets, tutorials, etc..)

**Comment by samdark** [comment]
You mean something like the following?

![ide](https://cloud.githubusercontent.com/assets/47294/11614440/e54e3600-9c53-11e5-8f43-9f51e4d466b1.png)

**Comment by jacmoe** [comment]
http://www.jiiframework.ru/img/slide-bg.jpg

**Comment by iJackUA** [comment]
I can propose something like this
![screenshot from 2015-12-06 21 13 19](https://cloud.githubusercontent.com/assets/568566/11615049/7301fbb2-9c5e-11e5-8ab4-69dd2dec0ce6.png)

**Comment by jacmoe** [comment]
Thanks @iJackUA :)
I am not sure what I am going to do to it, but I'll figure out something with Gimp - there must be a plugin or script for turning it into a fake monitor screen shot like on the Jii framework site. :)

**Comment by SilverFire** [comment]
Try http://instacod.es/

**Comment by jacmoe** [comment]
![yiicoding](https://cloud.githubusercontent.com/assets/85424/11615355/a8bc8786-9c5e-11e5-80d4-6c0e723e3938.jpg)
I have no idea what buttons to press :p

**Comment by jacmoe** [comment]
@iJackUA Could you maybe do a screenshot in jpeg as well, please?
The size was great, but the resolution should be a lot higher - don't optimize anything. As you can see, the processed image lacks clarity.

**Comment by iJackUA** [comment]
@jacmoe PNG quality is better than JPG and I was not doing any compression. Just did a window screenshot. And as I understand it will not have resolution bigger than the resolution of my screen. So could barely help with that.

**Comment by samdark** [comment]
@jacmoe note how the screen is rotated at jii website. Orientation is important.

**Comment by jacmoe** [comment]
Good idea.I'll give it a go or two tomorrow ;)

**Comment by jacmoe** [comment]
![yiicoding](https://cloud.githubusercontent.com/assets/85424/11638703/ac123596-9d28-11e5-9da0-b18a3c48ffbd.jpg)

**Comment by cebe** [comment]
nice!

**Comment by samdark** [comment]
Look good.

**Comment by iJackUA** [comment]
All these digital imitations are nothing, real photos rulez ! :D 
Giving away these photos to community, anyone fell free to use https://www.dropbox.com/sh/9b7yek5bqe5snwu/AAAPI8VG76vaT9wUYpx1ZC2la?dl=0   (but hurry up, I do not guaranty it to be placed in my dropbox forever)

Few examples. Sublime Text, Material Theme. I have tried light/dark color themes and angles:
![img_7631](https://cloud.githubusercontent.com/assets/568566/11695562/88d338b4-9eb8-11e5-9135-4388bfa2e898.JPG)
![img_7626](https://cloud.githubusercontent.com/assets/568566/11695578/950703f4-9eb8-11e5-97b9-ce18840fa78a.JPG)

If we really decide to use such a photo in design, I can do another one with selected file/php code, theme, angle etc.

**Comment by jacmoe** [comment]
@iJackUA You are awesome! :+1: :)

**Comment by samdark** [comment]
These are good!
