### ISSUE TITLE
Small inaccuracies in design

### ISSUE THREAD

**Issue by yusforgithub** [yiisoft-contrib/yiiframework.com#206]
1. Main menu in small resolutions (>=320px && < 1100px)
https://gyazo.com/5b4188e2bfb1b2452dbf5646b884f533

2. Page SignUp, resolution less 992px
https://gyazo.com/6a94d9ef47706b0defec480f7e05ca00

**Comment by jacmoe** [comment]
Good point!
If I get some computer time, I will take a stab at trying to fix it.

**Comment by machour** [comment]
Fixed in #430, can be closed
