### ISSUE TITLE
Guide HTML doesn't work well with mobile phones

### ISSUE THREAD

**Issue by Karbashevskyi** [yiisoft-contrib/yiiframework.com#211]
![default](https://user-images.githubusercontent.com/31188317/29496824-e7d7c748-85da-11e7-9317-0f9f1fc6daff.png)

**Comment by cebe** [comment]
unable to reproduce, which URL are you referring to?

**Comment by samdark** [comment]
Seems it's http://www.yiiframework.com/doc-2.0/yii-behaviors-sluggablebehavior.html

**Comment by samdark** [comment]
@Karbashevskyi what's the phone model and browser?

**Comment by cebe** [comment]
these will soon be gone and replaced by the new website.

**Comment by Karbashevskyi** [comment]
@samdark iphone 5, safari.
