### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by Eseperio** [yiisoft-contrib/yiiframework.com#213]
I have cloned the project and it throws a php compile error with message 
**Cannot use yii\db\ActiveRecord as ActiveRecord because the name is already in use**
in `yiiframework.com/models/Rating.php`
Commenting `use yii\db\ActiveRecord;` solves the problem temporary. Don´t know exactly if is a PHP bug or in somewhere there is an ActiveRecord declaration without namespace.

Apache/2.4.25 (Unix) OpenSSL/1.0.2j PHP/5.6.30 mod_perl/2.0.8-dev Perl/v5.16.3

**Comment by samdark** [comment]
When's the error is thrown? How to reproduce it?

**Comment by Eseperio** [comment]
Just after opening local domain "local.yiiframework.com" on a fresh install of the project following [instructions](https://github.com/yiisoft-contrib/yiiframework.com#installation-instructions). 
I´ve seen [this](https://stackoverflow.com/a/23879699/3218983) but i´m not using any cache system.

**Comment by samdark** [comment]
Probably it's something related to PHP version. We plan using PHP 7 on the server so maybe we've used something that's not 5.6 compatible,

**Comment by cebe** [comment]
fixed, thanks for reporting!
