### ISSUE TITLE
Code highlight bold font face missing

### ISSUE THREAD

**Issue by indeveler** [yiisoft-contrib/yiiframework.com#214]
Chrome (click to see original image): 
![image](https://user-images.githubusercontent.com/1275668/29882917-c5499d04-8dd8-11e7-9be7-3d053f42cdd5.png)

Firefox (click to see original image): 
![image](https://user-images.githubusercontent.com/1275668/29882993-fc41c660-8dd8-11e7-8722-b721003f67f7.png)

The reason of different behavior is missing of source code pro bold (only regular):
![image](https://user-images.githubusercontent.com/1275668/29883022-1b4e2008-8dd9-11e7-983f-e6dd8cbc18ff.png)

It makes browser to render font face with it's own rendering algorythm so there is a difference. And it doesn't look good when you see bold font with outside shadows (webkit algorythm). 

The solution is to add source code pro bold font face to assets.

**Comment by indeveler** [comment]
Source Code Pro [download page](https://www.fontsquirrel.com/fonts/source-code-pro)

**Comment by samdark** [comment]
Do you want to handle a pull request?

**Comment by indeveler** [comment]
Yes but I'm busy for couple of days both with this task and absolute div.

31 авг. 2017 г. 2:30 пользователь "Alexander Makarov" <
notifications@github.com> написал:

**Comment by samdark** [comment]
No hurry.
