### ISSUE TITLE
Need sample data

### ISSUE THREAD

**Issue by Eseperio** [yiisoft-contrib/yiiframework.com#215]
I´m working tweaking the current design and need sample data to continue. Tutorials, extensions, and news. 
![image](https://user-images.githubusercontent.com/5459366/29990152-3e407b1a-8f78-11e7-8acd-6068adf761d1.png)

**Comment by samdark** [comment]
Extension detail:

![qip shot - screen 653](https://user-images.githubusercontent.com/47294/30111039-e4fde1f0-9314-11e7-9eef-d65e1222dc89.png)

Wiki page (tutorial) detail:
![qip shot - screen 652](https://user-images.githubusercontent.com/47294/30111035-e4f8085c-9314-11e7-921b-dfff544b5920.png)

Front page lists:
![qip shot - screen 651](https://user-images.githubusercontent.com/47294/30111036-e4f956da-9314-11e7-8b26-173a8e4cf463.png)

News detail:
![qip shot - screen 650](https://user-images.githubusercontent.com/47294/30111037-e4f99370-9314-11e7-8e17-4099b46da119.png)

News at front page:
![qip shot - screen 649](https://user-images.githubusercontent.com/47294/30111040-e524600a-9314-11e7-86ea-2757034a85d4.png)

If you need texts, let me know.

**Comment by Eseperio** [comment]
Well, it could be better if i can have a few samples of database, only 3 or 4 extensions and wikis, in order to test a pseudoreal environment.

**Comment by samdark** [comment]
Sent via email.

**Comment by cebe** [comment]
I have added faker command which can now generate dummy data:

Set up DB with:

```php
./yii migrate/up
./yii fake-data
```
