### ISSUE TITLE
Not found exception when guide can´t be loaded

### ISSUE THREAD

**Issue by Eseperio** [yiisoft-contrib/yiiframework.com#216]
https://github.com/yiisoft-contrib/yiiframework.com/blob/d70b4b90e15d3d206e7ed8b665311c9e27811cc5/views/api/partials/_versions.php#L16

If guide is not loaded a `null` value is returned, then the method `$guide->getDownloadFile()` will throw an error exception (cannot access property of null).  If guide can`t be loaded (at least index) a 404 error should be displayed, because information is not really available. I think this exception should go [here](https://github.com/yiisoft-contrib/yiiframework.com/blob/f8f54e003513f870174eb7897b4f3e25edc89399/models/Guide.php#L51).

**Comment by samdark** [comment]
@Eseperio how to reproduce the issue as a user?

**Comment by Eseperio** [comment]
An interrupted `make docs` operation left me without index.data and other files, then when i clicked "guide" menu item that error was thrown.  Now works perfect, because i have all docs created.

**Comment by samdark** [comment]
Shouldn't ever happen in production.
