### ISSUE TITLE
Deprecate zip archives

### ISSUE THREAD

**Issue by samdark** [yiisoft-contrib/yiiframework.com#217]
Considering that everyone are using Composer nowadays... See https://twitter.com/sam_dark/status/904471958330511360

**Comment by samdark** [comment]
https://yii.slack.com/archives/C6H833X42/p1504519928000349

**Comment by Eseperio** [comment]
Packed distributions can be good for end uses, but a powerful framework like Yii, which its end users are people who knows programming does not need it. 

P.S.I can´t access Slack group.

**Comment by samdark** [comment]
@Eseperio use https://join.slack.com/t/yii/shared_invite/MjIxMjMxMTk5MTU1LTE1MDE3MDAwMzMtM2VkMTMyMjY1Ng

**Comment by samdark** [comment]
Not going to remove these for current version of framework.
