### ISSUE TITLE
Connection to the forum

### ISSUE THREAD

**Issue by cebe** [yiisoft-contrib/yiiframework.com#218]
Implement a forum connector to allow yii website communicate with the forum software.

- [ ] SSO with the forum, user logged into site should be logged in to forum automatically.
- [x] badges need to retrieve info about posts for a given user, see #164 (Implement [ForumAdapter](https://github.com/yiisoft-contrib/yiiframework.com/blob/423db110f27f20c763a5506e0fe66a4ac5c73cba/components/ForumAdapter.php))

**Comment by samdark** [comment]
Seems that the code should be adjusted a bit to be able to run under PHP 7.1.

**Comment by cebe** [comment]
which code?

**Comment by samdark** [comment]
- `\admin\sources\base\core.php`. Remove `0` prefixes from integers. PHP7 will error with these.
- In `initdata.php` comment out everything about magic quotes.

**Comment by samdark** [comment]
Tables that are to be filled to register a user.

## members

- name - name of the user
- member_group_id - id of the group (need to check what's the default one)
- joined, last_visit, last_activity - timestamp with creation date
- ip_address - user IP
- allow_admin_mails - 1
- hide_email - 1
- language - 1
- member_login_key - see below
- member_login_expire - timestamp + 1 week
- members_display_name, members_seo_name, members_l_display_name, members_l_username -nickname
- members_pass_hash - password hash, see below
- members_pass_salt - password salt, see below

Data generation methods:

```php
/**
	 * Generates a compiled passhash.
	 * Returns a new MD5 hash of the supplied salt and MD5 hash of the password
	 *
	 * @param	string		User's salt (5 random chars)
	 * @param	string		User's MD5 hash of their password
	 * @return	string		MD5 hash of compiled salted password
	 */
	static public function generateCompiledPasshash( $salt, $md5_once_password )
	{
		return md5( md5( $salt ) . $md5_once_password );
	}

    /**
     * Generates a password salt.
     * Returns n length string of any char except backslash
     *
     * @param	integer		Length of desired salt, 5 by default
     * @return	string		n character random string
     */
    static public function generatePasswordSalt($len=5)
    {
        $salt = '';

        for ( $i = 0; $i < $len; $i++ )
        {
            $num   = mt_rand(33, 126);

            if ( $num == '92' )
            {
                $num = 93;
            }

            $salt .= chr( $num );
        }

        return $salt;
    }

	/**
	 * Generates a log in key
	 *
	 * @param	integer		Length of desired random chars to MD5
	 * @return	string		MD5 hash of random characters
	 */
	static public function generateAutoLoginKey( $len=60 )
	{
		$pass = self::generatePasswordSalt( $len );

		return md5($pass);
	}
```

**Comment by samdark** [comment]
Implemented a bridge that is able to create new user. We currently assume that user ID is the same as forum ID and don't have a separate field in our primary table that stores forum user ID. @cebe I think we should add it and link users through it rather than making assumptions.

**Comment by cebe** [comment]
Currently the id is explicitly inserted, so it is the same. If your implementation does not ensure that, we need a separate column to store it.

**Comment by samdark** [comment]
My implementation does but if we won't import all the accounts from the forum (spam, for example), we won't be able to create users with such IDs.
