### ISSUE TITLE
extensions imported from packagist do not match version filter

### ISSUE THREAD

**Issue by cebe** [yiisoft-contrib/yiiframework.com#224]
versions from packagist currently populate Yii version with the version constraint.
The version selector does only allow selecting 1.1 and 2.0, which does not match the constraint.
We should extract a normalized version from the constraint.

**Comment by samdark** [comment]
I'll handle that.

**Comment by samdark** [comment]
Hmm... do you think we need the constraint itself?

**Comment by samdark** [comment]
Hmm... can't reproduce it. Which extension you were adding?
