### ISSUE TITLE
Can't sign in with github

### ISSUE THREAD

**Issue by vladyslavstartsev** [yiisoft-contrib/yiiframework.com#225]
I'm trying to login with github, but what I get is 
`Unable to save user: {"display_name":["Display Name cannot be blank."]}`
It looks like this
![image](https://user-images.githubusercontent.com/17382248/30800894-28c72412-a1ea-11e7-8132-91d8e132926f.png)

**Comment by cebe** [comment]
should be fixed by f09def4ba0c5ac08d1c1217c92eb1a51a33dc676, please try again!

**Comment by vladyslavstartsev** [comment]
@cebe no, the same thing. I've tried and also I've revoked access and tried again. I'm getting the same thing.

**Comment by cebe** [comment]
are you trying on a local copy, or on http://yiiframework.domain-na.me/? The demo site is not updated yet.

**Comment by vladyslavstartsev** [comment]
Oh. Sorry, my fault it was demo.
