### ISSUE TITLE
Subscribe to guide pages

### ISSUE THREAD

**Issue by cebe** [yiisoft-contrib/yiiframework.com#229]
currently you can only subscribe to extensions and wikis, however if you comment on a guide or api page, you get no notification. subscription should work there too.

**Comment by prodex** [comment]
Now Star (and Vote) refer to the object through `object_id`, where`object_id` is of type `integer`.

There are two options:
1) Make `object_id` to string, as implemented in the comments.
2) Create a `table` with the docs (guide, api) elements, to be able to refer to the `primary key`.

I'm for the second option. Maybe not everybody will agree with me)

**Comment by cebe** [comment]
Merged, thank you!
