### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by cebe** [yiisoft-contrib/yiiframework.com#23]
This issue lists things that need to be fixed for the site to work on mobile devices:

- [ ] Guide menu is completely hidden on mobile device. should become a dropdown like language and version instead.
- [ ] ...

**Comment by jacmoe** [comment]
I am looking into this right now :)
http://getbootstrap.com/examples/offcanvas/

**Comment by jacmoe** [comment]
Fixed by a0106374b4a0ceea06ef2a045797907dbb8f68af
