### ISSUE TITLE
Make sure contributors list is OK when GitHub is offline

### ISSUE THREAD

**Issue by samdark** [yiisoft-contrib/yiiframework.com#24]

**Comment by jacmoe** [comment]
I just committed a command  `./yii contributors/generate` that will generate (do'h) a *contributors.json* in the @app/data directory and generate thumbnails of the user avatars and put them in @app/data/avatars.

In 493f1748311c74c40c6221b14e8c800b42e3da66

I am working on stage 2 which is using Gulp to generate a sprite image using the avatar thumbnails and spit out a sprite image and a Sass file that can be (and will be) included and processed by our styles Gulp task.

That should take care of that, I think :)

**Comment by jacmoe** [comment]
![sprite](https://cloud.githubusercontent.com/assets/85424/13678724/745633c0-e6f0-11e5-8131-91d592f384ad.png)

**Comment by jacmoe** [comment]
Do you have any size preferences?

24px is good, but maybe too tiny ?

**Comment by jacmoe** [comment]
So, 48 :

![sprite](https://cloud.githubusercontent.com/assets/85424/13678807/ee0e56d4-e6f0-11e5-9396-caf2ee4da72d.png)

**Comment by jacmoe** [comment]
And with padding:
![sprite](https://cloud.githubusercontent.com/assets/85424/13678930/963ccb56-e6f1-11e5-832d-62e2f5d30660.png)

Now, all that remains is to marry the sprite with the generated CSS :)

**Comment by jacmoe** [comment]
Btw, the sprites are brought to you by [gulp.spritesmith](https://github.com/twolfson/gulp.spritesmith)

**Comment by samdark** [comment]
Looks perfect.

**Comment by samdark** [comment]
Can you add it to readme not to forget to set up cron for it?

**Comment by jacmoe** [comment]
I will when it's done :)

**Comment by jacmoe** [comment]
![sprite](https://cloud.githubusercontent.com/assets/85424/13682351/ae2b68ac-e701-11e5-9562-3bd0c49070a6.png)

Moved the Github API code out of the SiteController and into the ContributorsController - for some reason Curl only returned a smaller list.

**Comment by jacmoe** [comment]
Added a note.

This probably needs some code review, which is why I leave this issue as open. ;)

**Comment by jacmoe** [comment]
The team page now loads almost instantaneous :speedboat:

**Comment by cebe** [comment]
Awesome job! deploying this to the demo site right now.

> for some reason Curl only returned a smaller list.

the reason is pagination.

**Comment by jacmoe** [comment]
> the reason is pagination.

The result, however, is that I got to reuse the existing code for grabbing the contributor list - it just moved from one controller to another :p

**Comment by cebe** [comment]
yeah, seen that.

**Comment by cebe** [comment]
looks great to me, I think this can be closed. Thank you @jacmoe !

**Comment by jacmoe** [comment]
Awesome! :+1:

Now I can stop holding my breath - the new team page sure is speedy. :)
