### ISSUE TITLE
design improvements

### ISSUE THREAD

**Issue by allyraza** [yiisoft-contrib/yiiframework.com#242]
I have few ideas, I see improvements can be made to the current design I have been putting together a list of urls just to get ideas that we can use on yii's new site. look at laravel's homepage for example see the design is really elegant they are making use of space very nicely as well as the typography helps make the design nice and good looking. please look at the links below.

http://laravel.com
really nice looking design.

https://dribbble.com/shots/3090809-Landing-page/attachments/652287
I found this to be attractive in terms of how they laid out the feature cards.

https://designmodo.com/slides/
this design has very elegant hero section and navigation is also nice

https://shopify.github.io/Timber/
I really like this for the docs scroll just below the hero you will see the docs section done very nicely.

and few more points, perhaps we can adopt some of these ideas to put together a better design for yii's new site.

 what to you think?

@alexjcollins another yii comunity member is also involved in doing the design.

**Comment by samdark** [comment]
Any improvements are welcome after initial website launch.

**Comment by alexjcollins** [comment]
@samdark Thanks, understood.

**Comment by samdark** [comment]
It's launched now.
