### ISSUE TITLE
header is black

### ISSUE THREAD

**Issue by cebe** [yiisoft-contrib/yiiframework.com#250]
figure out why:

![bildschirmfoto von 2018-03-01 11-48-44](https://user-images.githubusercontent.com/189796/36842373-c79915d2-1d4b-11e8-9f48-22eeccc5a3d8.png)

**Comment by samdark** [comment]
Not a showstopper though...

**Comment by samdark** [comment]
Should be like http://yiiframework.domain-na.me/ i.e. blue:

![opera snapshot_2018-03-01_144934_yiiframework domain-na me](https://user-images.githubusercontent.com/47294/36843370-ccfea280-1d5f-11e8-8358-e4cd2dd56c3a.png)
