### ISSUE TITLE
Improve Mobile Style

### ISSUE THREAD

**Issue by cebe** [yiisoft-contrib/yiiframework.com#256]
There are some issues in mobile CSS of the site that should be fixed.

- [x] Guide/API: Code snippets and info boxes use too much space on the left, reduce padding/margin ![screenshot_2018-03-08-21-42-41](https://user-images.githubusercontent.com/189796/37176628-3941eb38-231d-11e8-8ff0-dffeb3e3d56a.png)
- [ ] same as above for list indentation ![screenshot_2018-03-08-21-48-32](https://user-images.githubusercontent.com/189796/37176630-398c2536-231d-11e8-989c-6724135d2107.png)

- [x] Guide/API: Github info box could use full width ![screenshot_2018-03-08-21-46-39](https://user-images.githubusercontent.com/189796/37176629-3968945e-231d-11e8-8bbc-a06f0540a1b2.png)

- [x] API: Content in tables is not visible, also not via scrolling ![screenshot_2018-03-08-21-48-42](https://user-images.githubusercontent.com/189796/37176631-39afae48-231d-11e8-9811-f72211ed8c02.png)

- [ ] Wiki: index page is not clear about where one items ends and the other starts ![screenshot_2018-03-08-21-49-58](https://user-images.githubusercontent.com/189796/37176632-39cdb1d6-231d-11e8-9291-75ea42cdb298.png)

- [ ] Wiki: hide category and tags list when showing view page of an article, only show these on the index page ![screenshot_2018-03-08-21-51-12](https://user-images.githubusercontent.com/189796/37176636-39f1fd34-231d-11e8-9386-519f7c3a3f89.png)

- [ ] Extensions: items on index page use a lot of empty space ![screenshot_2018-03-08-21-51-34](https://user-images.githubusercontent.com/189796/37176638-3a1711aa-231d-11e8-89f9-31107d2b9022.png)

- [ ] Community members table is cut off ![screenshot_2018-03-08-21-55-22](https://user-images.githubusercontent.com/189796/37176640-3a342588-231d-11e8-9ab4-cfd7ff5b6e8b.png)

- [ ] Hall of fame content is aligned weirdly ![screenshot_2018-03-08-21-55-44](https://user-images.githubusercontent.com/189796/37176641-3a4fcc0c-231d-11e8-906d-dc6a03255ef1.png)

- [ ] Download page headline overflow ![screenshot_2018-03-08-21-58-43](https://user-images.githubusercontent.com/189796/37176642-3a6f9af0-231d-11e8-8d3b-7d35449de092.png)

- [x] Download page text overflow ![screenshot_2018-03-08-21-58-57](https://user-images.githubusercontent.com/189796/37176644-3a93daaa-231d-11e8-8b99-d5fcd2c3be2c.png)

- [ ] Contribute page headline overflow ![screenshot_2018-03-08-22-01-12](https://user-images.githubusercontent.com/189796/37176646-3ae08116-231d-11e8-953a-e47bbe4cb5d3.png)

- [ ] Extension alignment on "report issue" page has unnecessary spacing. ![screenshot_2018-03-08-22-00-24](https://user-images.githubusercontent.com/189796/37176645-3ababe18-231d-11e8-8a35-6c6dc93085bb.png)

**Comment by Arhell** [comment]
- [x] API: Content in tables is not visible, also not via scrolling - Fixed
[PR](https://github.com/yiisoft-contrib/yiiframework.com/pull/477)

**Comment by Arhell** [comment]
fix this https://www.yiiframework.com/doc/api/2.0/yii-helpers-basehtml#activeDropDownList()-detail
no overflow
![fe341047f1](https://user-images.githubusercontent.com/26163841/76141067-88bad680-6069-11ea-8949-6bffb8b91815.jpg)

**Comment by Arhell** [comment]
- [x] Guide/API: Github info box could use full width
#481
![538bbc89f8](https://user-images.githubusercontent.com/26163841/76169744-f65b2580-6183-11ea-85e5-84913f57bbbe.jpg)

**Comment by Arhell** [comment]
- [x] Guide/API: Code snippets and info boxes use too much space on the left, reduce padding/margin
![1](https://user-images.githubusercontent.com/26163841/77223177-d30c7f00-6b62-11ea-9bac-53e67f12e0a2.jpg)

**Comment by Arhell** [comment]
- [x] Download page text overflow
![aca2e00700](https://user-images.githubusercontent.com/26163841/77261134-fe8f8680-6c94-11ea-9087-5708d789c852.jpg)
PR -

**Comment by samdark** [comment]
Seems everything is fixed from this issue. Thank you, @Arhell!
