### ISSUE TITLE
Difficulty in reading namespace due to color changes

### ISSUE THREAD

**Issue by InsaneSkull** [yiisoft-contrib/yiiframework.com#264]
![screenshot-2018-3-23 api documentation for yii 2 0](https://user-images.githubusercontent.com/14233668/37829743-4e5966cc-2ec6-11e8-98a2-dbd45a21b4f4.png)

**Comment by samdark** [comment]
Any idea how to fix it? Plain black color or more bright colors?

**Comment by InsaneSkull** [comment]
I guess, plain black color is easily readable and noticed.

**Comment by InsaneSkull** [comment]
Old color looks good. Especially for sidebar

![screenshot-2018-3-23 yii framework 2 0 api documentation](https://user-images.githubusercontent.com/14233668/37829992-19e69422-2ec7-11e8-9910-c912df261530.png)

**Comment by Eseperio** [comment]
Color is not useful on this case.  Keeping all in gray and increasing the font-size at least 1px (current is 13px. too small for an index).

![image](https://user-images.githubusercontent.com/5459366/38169164-f366d8c8-3562-11e8-800b-9b42f8ca1ef9.png)
