### ISSUE TITLE
Follow button should appear only to logged in users

### ISSUE THREAD

**Issue by InsaneSkull** [yiisoft-contrib/yiiframework.com#266]
![screenshot-2018-3-23 api documentation for yii 2 0 1](https://user-images.githubusercontent.com/14233668/37830906-b6d2fef4-2ec9-11e8-8157-16831176a713.png)

Click on this results in 

![screenshot from 2018-03-23 18-32-31](https://user-images.githubusercontent.com/14233668/37830927-c6d0ea78-2ec9-11e8-8900-144876b1fc11.png)

Then redirects to

https://yiiframework.com/login

**Comment by samdark** [comment]
It should not error but I think redirecting to login is fine.
