### ISSUE TITLE
Help link in Gii sending to 404 error

### ISSUE THREAD

**Issue by d3v3r73e** [yiisoft-contrib/yiiframework.com#267]
Maybe bug of installing new design to`https://www.yiiframework.com`
After clicking on "Help" link in Gii (from local project) user is sending to `https://www.yiiframework.com/doc-2.0/ext-gii-index.html` with 404 error.
![screenshot_2018-03-23_16-59-01](https://user-images.githubusercontent.com/36017720/37833400-3c116b0e-2ebc-11e8-8e71-d0f298382cf7.png)
![screenshot_2018-03-23_17-00-08](https://user-images.githubusercontent.com/36017720/37833401-3c468d70-2ebc-11e8-9685-9d796f19af08.png)

**Comment by cebe** [comment]
same as #275
