### ISSUE TITLE
SSL certificate and forcing HTTPS

### ISSUE THREAD

**Issue by samdark** [yiisoft-contrib/yiiframework.com#27]
http://www.yiiframework.com/forum/index.php/topic/62964-https/

**Comment by bethrezen** [comment]
Why not to try https://letsencrypt.org/ or use free certificate from http://www.startssl.com/?app=1 ?

**Comment by samdark** [comment]
Let's encrypt sounds good.

**Comment by cebe** [comment]
I'd go with letsencrypt too.

**Comment by SilverFire** [comment]
+1

**Comment by cebe** [comment]
even though our case is much simpler, here are some points to consider: https://nickcraver.com/blog/2013/04/23/stackoverflow-com-the-road-to-ssl/
e.g. mixed content, user contributed images etc.

**Comment by sam002** [comment]
I have extension for working with ACME protocol: https://github.com/sam002/yii2-acme
The certificates can be issued and updated with yii console. You can connect any ACME provider, including letsencript.
_Will be grateful for their help in testing))_

**Comment by cebe** [comment]
Thanks for sharing! I have been using https://github.com/Neilpang/acme.sh which seems well tested and worked good so far. Imo ACME should be deployed independent of Yii as it has to deploy SSL certs and private keys. The webserver process running Yii should not have write permission on these.

**Comment by sam002** [comment]
@cebe Write access will be only in the case of running by the relevant user/group. Usage the extension is justified when a large number of domains and single application or domains is dynamically (exmpl: cdn, subdomains usage).

**Comment by jacmoe** [comment]
Have you checked out Certbot? -> https://certbot.eff.org/

**Comment by cebe** [comment]
I have, but it is way too complex for the case where I wanted to use it. It did not install because of conflicting dependencies. acme.sh is dependency free except the shell :)

**Comment by samdark** [comment]
It's now done.
