### ISSUE TITLE
Broken links at download page

### ISSUE THREAD

**Issue by samdark** [yiisoft-contrib/yiiframework.com#280]
https://www.yiiframework.com/download

Links to download Yii 2 are broken.

**Comment by cebe** [comment]
Oops, 2.0.15 being kind of a patch release, I forgot to release the applications :)

**Comment by cebe** [comment]
Need to automate this better :)

**Comment by cebe** [comment]
uploaded 2.0.14 apps with 2.0.15.1 installed.
