### ISSUE TITLE
RBAC assignments are lost when running rbac/up

### ISSUE THREAD

**Issue by cebe** [yiisoft-contrib/yiiframework.com#283]
deployment runs rbac/up to ensure roles and permissions are up to date. Assignments are currently reset by this operation. We need a way to keep rbac assignments.

**Comment by samdark** [comment]
The code is correct. The issue is with DB's `ON DELETE CASCADE` that deletes assignments as soon as role is deleted. We may switch to file-based backend to fix it.

**Comment by samdark** [comment]
Alternatively we can back up all assignments and re-apply them but that's a bit more complicated.
