### ISSUE TITLE
In guide all widget links is broken

### ISSUE THREAD

**Issue by CavidM** [yiisoft-contrib/yiiframework.com#287]
https://www.yiiframework.com/doc/guide/2.0/en/yii-grid-gridview.html
https://www.yiiframework.com/doc/guide/2.0/en/yii-widgets-listview.html
https://www.yiiframework.com/doc/guide/2.0/en/yii-widgets-linksorter.html

**Comment by cebe** [comment]
where did you find these links? They should point to api docs instead of guide.

**Comment by InsaneSkull** [comment]
@cebe  confirmed. Under https://www.yiiframework.com/doc/guide/2.0/en WIDGETS section points to wrong url. For example Gridview Widget current link  https://www.yiiframework.com/doc/guide/2.0/en/yii-grid-gridview.html but should point to https://www.yiiframework.com/doc/api/2.0/yii-grid-gridview

Unfortunately, couldn't figured out , how to solve it. :disappointed:

**Comment by schmunk42** [comment]
I ran linkchecker against the first three levels:

[check.zip](https://github.com/yiisoft-contrib/yiiframework.com/files/1851444/check.zip)

Ignore the 403s.
