### ISSUE TITLE
Changing password does not update forum password

### ISSUE THREAD

**Issue by samdark** [yiisoft-contrib/yiiframework.com#292]

**Comment by samdark** [comment]
Related to #286

**Comment by rugabarbo** [comment]
What if the user changes the password on the forum?
Will it be changed a password on the site?

**Comment by samdark** [comment]
Nope.

**Comment by rugabarbo** [comment]
Hmm... Is it possible to do?

**Comment by samdark** [comment]
Yes but I'd not spend time on that. We're going to move to another forum engine as soon as we'll stabilize website a bit.
