### ISSUE TITLE
Some list items are lost when rendered in Japanese

### ISSUE THREAD

**Issue by softark** [yiisoft-contrib/yiiframework.com#294]
![scrn-1](https://user-images.githubusercontent.com/342857/37895572-ac170e6a-311c-11e8-8cd3-3f1954250e58.png)
https://www.yiiframework.com/doc/guide/2.0/ja/caching-data

As you see in the screen shot, some list item in an un-ordered list get lost in a Japanese document.

While github markdown renders the source of it just right.

![scrn-3](https://user-images.githubusercontent.com/342857/37895730-26cc8d24-311d-11e8-8d50-058e77d70493.png)
https://github.com/yiisoft/yii2/blob/master/docs/guide-ja/caching-data.md

**Comment by samdark** [comment]
Which browser it that? Rendered well in Chrome/Opera.

**Comment by samdark** [comment]
https://www.yiiframework.com/doc/guide/2.0/ja/caching-data

**Comment by samdark** [comment]
Since there's no HTML, I suppose it could be a bug in https://github.com/cebe/markdown

**Comment by softark** [comment]
I agree. An extra feature for Yii documentation might have some bug.
But I don't understand why only Japanese.

**Comment by samdark** [comment]
Complicated multibyte sequences, I guess...

**Comment by cebe** [comment]
no, syntax conflict with markdown reference and our custom syntax. fixed via https://github.com/cebe/markdown/commit/bf05759a8781b457a89a97aa2d8f17e5604224e8

**Comment by cebe** [comment]
@softark thanks for reporting!

**Comment by softark** [comment]
@cebe Great! Thank you for the quick fix.
