### ISSUE TITLE
Extension and Wiki Article : popular tags  doesn't have reset filter or say all option

### ISSUE THREAD

**Issue by InsaneSkull** [yiisoft-contrib/yiiframework.com#296]
![screenshot-2018-3-26 extensions](https://user-images.githubusercontent.com/14233668/37901489-f6c9bbb4-310e-11e8-8f6e-bda146f2a945.png)

Once we click on popular tag filter, there is no way back, except we manually remove from url ;)

![screenshot-2018-3-26 extensions 1](https://user-images.githubusercontent.com/14233668/37901589-53f93d64-310f-11e8-92f6-1d41fbd6cd0e.png)

**Comment by InsaneSkull** [comment]
@samdark  @cebe

**Comment by samdark** [comment]
Shouldn't be releated.

**Comment by InsaneSkull** [comment]
That's what i guess but please give it a try using revert my pull requests

**Comment by samdark** [comment]
Ah, right. Fixed in master.

**Comment by samdark** [comment]
https://github.com/yiisoft-contrib/yiiframework.com/commit/d8c5b2353013d619b1cde436a0b2892a0608a7d0
