### ISSUE TITLE
User Contributed Notes Design Issue

### ISSUE THREAD

**Issue by vishuB** [yiisoft-contrib/yiiframework.com#297]
![user contributed notes design issue](https://user-images.githubusercontent.com/13677102/37902080-e35be9e2-3110-11e8-8154-4e173f6c5f0c.png)

**Comment by samdark** [comment]
Hmm... that overlay thing was actually intended. How would you like it to be?

**Comment by hirenbhut93** [comment]
@samdark Move the user name and time in footer, only id can show in top

**Comment by samdark** [comment]
OK. Would you like to make a pull request with a fix?

**Comment by cebe** [comment]
fixed by #302
