### ISSUE TITLE
news page renders a TOC in wrong position

### ISSUE THREAD

**Issue by cebe** [yiisoft-contrib/yiiframework.com#303]
https://www.yiiframework.com/news/168/releasing-yii-2-0-15-and-database-extensions-with-security-fixes

![bildschirmfoto von 2018-03-26 16-54-36](https://user-images.githubusercontent.com/189796/37913997-7c08ccd2-3116-11e8-8171-2b1159035e27.png)

**Comment by cebe** [comment]
also seen here https://www.yiiframework.com/wiki/628/overrideeliminate-bootstrap-cssjs-for-yii-2-0-widgets

**Comment by machour** [comment]
Will be fixed by upgrading yii2-apidoc after https://github.com/yiisoft/yii2-apidoc/pull/177 is merged

**Comment by samdark** [comment]
It's merged but wasn't tagged yet.
