### ISSUE TITLE
RSS - Keep receiving news on slack about extensions but only wants yii web news

### ISSUE THREAD

**Issue by sebathi** [yiisoft-contrib/yiiframework.com#308]
Hi! 

RSS is keeping updating and give me more than 300 messages on slack this 4 days :(

Messages keep coming and no way to stop them. 

Regards,

**Comment by samdark** [comment]
Slack?

**Comment by cebe** [comment]
we could separate RSS files into different categories.

**Comment by sebathi** [comment]
I think it has something to do with the updatedDate on the rss field.

![image](https://user-images.githubusercontent.com/1434034/38050426-5c7a893c-32a1-11e8-8434-b52d960b17c0.png)

**Comment by samdark** [comment]
Nope. It's launch of the new website. Adding extensions is now simpler so more are added.

**Comment by sebathi** [comment]
270 in 1 day? I think the issue is the update time on the extensions. Every download will update the updated at used at [`https://github.com/yiisoft-contrib/yiiframework.com/blob/master/controllers/RssController.php#L123`](https://github.com/yiisoft-contrib/yiiframework.com/blob/master/controllers/RssController.php#L123)

**Comment by sebathi** [comment]
A pull request with the issue (RSS info is changing)

![2018-03-28 16 37 14](https://user-images.githubusercontent.com/1434034/38052254-04efaa3e-32a7-11e8-8aeb-4580f77ffb4f.gif)

**Comment by samdark** [comment]
Ah... same extension is duplicated...

**Comment by samdark** [comment]
I think it may be your client that does so. I've added feed to feedly.com. Will see how it goes.

**Comment by sebathi** [comment]
178 times ;)

On Wed, Mar 28, 2018 at 4:48 PM, Alexander Makarov <notifications@github.com

**Comment by samdark** [comment]
First of all, need to make sure it is validated well: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.yiiframework.com%2Frss.xml

**Comment by samdark** [comment]
Fixed minor stuff. The rest should not affect your duplicates (timestamps are correct) so it seems that's the client that is behaving weird. Feedly is alright.

**Comment by samdark** [comment]
Closing since having multiple feed types won't help in your situation.
