### ISSUE TITLE
make docs fails on PHP7.2 because "Object"

### ISSUE THREAD

**Issue by Eseperio** [yiisoft-contrib/yiiframework.com#311]
**Make docs**  triggers an error when rendering files because asset manager is trying to load bootstrap assets from `vendor/bower` instead `vendor/bower-asset`. 
![image](https://user-images.githubusercontent.com/5459366/38103910-f1e18872-3387-11e8-86b7-ba08fa7ee1b6.png)

Also **make docs** fails if it is executed under php 7

**Comment by cebe** [comment]
thats weird, it works for me and also on the production server... also PHP 7, latest version of composer (1.6.3).

**Comment by Eseperio** [comment]
@cebe Fails under Php7.2 because phpDocumentor parse the deprecated *Object* class

**Comment by cebe** [comment]
we need to keep docs for that one so we need to stay on php <7.2 for generating docs.

**Comment by machour** [comment]
Had the originally reported problem right now, using PHP 7.1.25

```
./yii api "2.0" --interactive=0
Start generating API 2.0...
Searching files to process... done.
Loading apidoc data from cache... no data available.
Checking for updated files... done.
432 files to update.
Processing files... done.
Updating cross references and backlinks... done.
Rendering files: 0% (0/433) ETA: n/a   Exception 'yii\base\InvalidArgumentException' with message 'The file or directory to be published does not exist: /Users/didou/oss/yiisoft-contrib/yiiframework.com/vendor/bower/bootstrap/dist'

in /Users/didou/oss/yiisoft-contrib/yiiframework.com/vendor/yiisoft/yii2/web/AssetManager.php:456
```
