### ISSUE TITLE
Неверное отображение количество статей по категория и тегам

### ISSUE THREAD

**Issue by lesha724** [yiisoft-contrib/yiiframework.com#316]
1. Ошибочное отображение количества статей по категории и тегам, например на скринах выбран тег yii2: в фильтрах (в sidebar) показывает 83, а так 78.
2. Может нужно сделать что бы в sidebar количество отображалось в зависимости от выбранных фильтров(категории, фильтров) или хотя бы от версии. 

![first](https://user-images.githubusercontent.com/8524434/38165988-e9444ba2-3524-11e8-8793-7a1b4acd2344.PNG)
![second](https://user-images.githubusercontent.com/8524434/38165989-e97d1b94-3524-11e8-8cda-1eeb799cc3ae.PNG)

**Comment by lesha724** [comment]
Пример с категорией 171 и 154
![third](https://user-images.githubusercontent.com/8524434/38166056-f1c6efc2-3525-11e8-91af-2e1f6369cecc.PNG)

**Comment by cebe** [comment]
related to #269
