### ISSUE TITLE
Bug on Api version dropdown link

### ISSUE THREAD

**Issue by Eseperio** [yiisoft-contrib/yiiframework.com#319]
In api view when browsing apidoc for 1.x the link for version 2.x is wrong.
As an example try to switch [here](https://www.yiiframework.com/doc/api/1.1/CMemCache) to apidocs v2.0

**Comment by samdark** [comment]
There's no such page in 2.0 docs. We probably need custom 404 page there that offers to go to index page of the guide.

**Comment by cebe** [comment]
I made some changes while developing api docs for extensions, please check if it works as expected now.

**Comment by Eseperio** [comment]
Now works as expected.
