### ISSUE TITLE
[Question] Horizontal filters

### ISSUE THREAD

**Issue by Eseperio** [yiisoft-contrib/yiiframework.com#321]
What do you think about having horizontal filters instead a left column?  
This will consist on a series of dropdown combined with checkboxes. Each selection is rendered as a tag, and can be easily removed. This will left more space for content and an easy way to find which filters are applied.

I have this done in other project.
![image](https://user-images.githubusercontent.com/5459366/38172953-e649c972-35b5-11e8-8558-6843c7dd158f.png)

**Comment by samdark** [comment]
Depends on what page we're talking about.

**Comment by Eseperio** [comment]
Wiki

**Comment by samdark** [comment]
That's extra clicks and scrolling. Doesn't sound good to me and we're not really saving since central column currently has optimal line length.
