### ISSUE TITLE
wiki - markdown preview button is not work in chrome browser

### ISSUE THREAD

**Issue by vishuB** [yiisoft-contrib/yiiframework.com#330]
Chrome Version 65.0.3325.162 (Official Build) (64-bit)

**Comment by samdark** [comment]
Any errors in console? Which URL is that?

**Comment by samdark** [comment]
Since I've developed it using Chrome I assume it's gulp build issue. @cebe

**Comment by cebe** [comment]
works for me in Chromium `Version 57.0.2987.98 Built on 8.7, running on Debian 8.10 (64-bit)`. what exactly is not working?

**Comment by vishuB** [comment]
Show below image

![markdown](https://user-images.githubusercontent.com/13677102/38306902-a6eba558-382f-11e8-9e30-2ae9c3b31bba.png)

**Comment by cebe** [comment]
works as expected for me. could you provide more details about what the ajax request returns?

**Comment by cebe** [comment]
![bildschirmfoto von 2018-04-04 14-34-16](https://user-images.githubusercontent.com/189796/38307877-86f3f9d6-3815-11e8-8d0a-7737df9b0fa2.png)

**Comment by vishuB** [comment]
![markdown](https://user-images.githubusercontent.com/13677102/38308017-5d2af5aa-3833-11e8-89b6-936a13962773.png)

**Comment by vishuB** [comment]
@cebe please update youre chrome version and check

**Comment by hirenbhut93** [comment]
Yes @cebe  this is not working in chrome 61 also.

**Comment by cebe** [comment]
Mine is the version that comes with debian, not easy to upgrade without upgrading the system. @samdark what is your chrome version?

**Comment by samdark** [comment]
65.0.3325.181 (Official Build) (64-bit). Works well.

**Comment by cebe** [comment]
@vishuB @hirenbhut93 we discovered some issues with clearing browser cache of CSS and JS files. That should be solved now. Could you please verify it is not realted to old cached JS/CSS files?

**Comment by vishuB** [comment]
yes
