### ISSUE TITLE
trim input in search field

### ISSUE THREAD

**Issue by cebe** [yiisoft-contrib/yiiframework.com#337]
searching for `.batchInsert()` works as expected but if you add whitespace in front or after it, search results are empty.

**Comment by cebe** [comment]
the syntax is explained on the api index page: https://www.yiiframework.com/doc/api/2.0

> **You can search API documentation using the search form on the top.** You can search for class names and also method and property names, e.g. ActiveRecord.save() or just .save() or ::save().

**Comment by cebe** [comment]
but if we can improve the behavior to be more intuitive, I am all for it.

**Comment by cebe** [comment]
here is the code responsible for it: https://github.com/yiisoft-contrib/yiiframework.com/blob/de63bcdd930e4e745763fae2bfc2005d7f4a1fa7/assets/src/js/search.js#L79-L155

**Comment by rob006** [comment]
Can't we just join results of regular search and "dot-search"? Searching `batchInsert` will return results for `batchInsert` and additionally results for `.batchInsert` at the end.

**Comment by cebe** [comment]
need to play with it a bit to see if that makes sense from the results it shows, but that would be an option.
