### ISSUE TITLE
API: Method description overflow the page

### ISSUE THREAD

**Issue by rob006** [yiisoft-contrib/yiiframework.com#338]
https://www.yiiframework.com/doc/api/2.0/yii-helpers-basehtml#activeDropDownList()-detail

![e7e1acb1](https://user-images.githubusercontent.com/5972388/38578817-557e0e2e-3d05-11e8-9b63-bce80d068b4c.png)

**Comment by cebe** [comment]
there is `white-space: pre;` css style on `.hljs` class which causes the table to grow, should be changed to `pre-wrap` instead. But list style seems to be broken too.

**Comment by rob006** [comment]
> should be changed to pre-wrap instead

This may kill readability. Usually horizontal scroll is used for code blocks.

**Comment by Arhell** [comment]
resolve
