### ISSUE TITLE
Forum: User registration does not work (is blocked) from within forum

### ISSUE THREAD

**Issue by Forin** [yiisoft-contrib/yiiframework.com#348]
If a visitor opens the forum and klicks on "register now" the following message appears:

**[#10123] The administrator is currently not accepting new membership registrations.**

There are no new registrations/forum users since 5th of April.

**Comment by samdark** [comment]
Indeed, it is disabled. We should clearly communicate that registering at the website creates a forum user for you...

**Comment by cebe** [comment]
"register now" does redirect to the website signup form now, so the confusion around this should be resolved. Same for password reset.

- https://www.yiiframework.com/forum/index.php?app=core&module=global&section=register :arrow_right: https://www.yiiframework.com/signup
- https://www.yiiframework.com/forum/index.php?app=core&module=global&section=lostpass :arrow_right: https://www.yiiframework.com/auth/request-password-reset
