### ISSUE TITLE
i have a problem : Missing a table'ipb_members'

### ISSUE THREAD

**Issue by thinkwcz** [yiisoft-contrib/yiiframework.com#356]
Database Exception – yii\db\Exception
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'yiiframeworkcom.ipb_members' doesn't exist
The SQL being executed was: SELECT `member_id` FROM `ipb_members` WHERE `email`='user01@qq.com'
Error Info: Array
(
    [0] => 42S02
    [1] => 1146
    [2] => Table 'yiiframeworkcom.ipb_members' doesn't exist
)

how to solve the problem?

**Comment by thinkwcz** [comment]
No, I don't have the source code.
So it is. I see, Thanks.

**Comment by samdark** [comment]
We can probably make it possible to turn off the forum integration so contributors won't have to install IPB.

**Comment by rob006** [comment]
Or at least provide some test database dump.

**Comment by thinkwcz** [comment]
That's a good idea.

**Comment by samdark** [comment]
Added DummyAdapter. Configure it in your params-local.php to work w/o a forum DB.
