### ISSUE TITLE
Where and how to store users?

### ISSUE THREAD

**Issue by samdark** [yiisoft-contrib/yiiframework.com#36]
It seems we have a problem with users.

- We have at least 2 different domains: yiicamp.com and yiiframework.com.
- User should be identified across these domains.
- Some common data such as avatar, first and last name should be shared.

Additionally there are third party Yii-related projects such as language-specific community websites that will benefit from it.

Any suggestions on the solution?

**Comment by cebe** [comment]
Working on porting the existing user system to the site, so yiiframework.com will be the main account website and forum and/or other sites will take the login from there.
