### ISSUE TITLE
Avast antivirus support phone anyone?

### ISSUE THREAD

**Issue by mikk150** [yiisoft-contrib/yiiframework.com#369]
https://www.yiiframework.com/search?q=SECURITY+185.5.392.21.11+avast+antivirus+support+p&page=1

I was searching in API doc for `yii\base\Security` and last other results answer was quite... interesting...

**Comment by samdark** [comment]
Not that again :(

**Comment by samdark** [comment]
Seems it's in the search index only.

**Comment by cebe** [comment]
somehow the search manages to link to itself instead of a wiki page. need to check what is wrong there.

**Comment by samdark** [comment]
These are deleted wiki pages that I've cleaned up after index was built (I think).

**Comment by cebe** [comment]
index is rebuilt regularily so we should check why they are not cleared

**Comment by samdark** [comment]
Is it re-built (cleaned and then entities added) or updated (entities added and refreshed)?

**Comment by samdark** [comment]
Yes. It was index. Re-created it.
