### ISSUE TITLE
use stable version for `HelgeSverre/SpamProtection`

### ISSUE THREAD

**Issue by cebe** [yiisoft-contrib/yiiframework.com#375]
current version of https://github.com/HelgeSverre/SpamProtection has a broken file name, so [we use `dev-master` in composer.json](https://github.com/yiisoft-contrib/yiiframework.com/commit/3e4f60bdc0ae317156759d3c5a267d7c36343134). Change that when https://github.com/HelgeSverre/SpamProtection/issues/3 is fixed.

**Comment by cebe** [comment]
@HelgeSverre thanks, I have seen it, just not got to using it yet :)

**Comment by machour** [comment]
Fixed in https://github.com/yiisoft-contrib/yiiframework.com/commit/c747fdc09c7440e52c5faf21168a5ad511b6a8f9#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780 by @samdark
