### ISSUE TITLE
improve / adjust API Documentation Search

### ISSUE THREAD

**Issue by jjdunn** [yiisoft-contrib/yiiframework.com#379]
In the old version of API documentation, the Search feature was very helpful.  Now, the Search feature is less helpful.  Please consider restoring some of the old functionality.

In particular:
 1. there is no valid reason to require the class-name, or "." or "::" prefix in order to find a method.  Typing "beforeSave" should find the beforeSave() method anywhere it is implemented
 2. there is no way to find class Properties in the Search box now;  but I think they used to be available.  Try searching for "scenario" and it shows nothing; but the "scenario" property exists in CActiveRecord (v1.1).  Please add/restore this feature.
 3. if my browser window is too narrow, I get the responsive-design for mobile, which makes no sense in a desktop browser.  It's switching to mobile around 1060px, which is far too wide.  I might typically have my browser window sized around 850px, at which point I get the mobile design which makes using the Search feature take more clicks and looks very weird in a desktop environment. 
 4. I found the Search feature more useful when it was in the middle of the page.  It's slightly harder to access in the upper-right corner. 

Thanks very much for considering these requests / suggestions.

Jeremy Dunn
Yii user ("Jeremy") since 2010
still using v1.1 for several projects

**Comment by jjdunn** [comment]
![yiiframework-api-windows2008r2-remote-desktop](https://user-images.githubusercontent.com/333222/43266867-7095ed72-90ba-11e8-9b2c-f141e80b8220.PNG)
![yiiframework-api-window7-local](https://user-images.githubusercontent.com/333222/43266874-7226f6c2-90ba-11e8-855a-d03006604543.PNG)

see attached two screenshots of the Framework API documentation page.  I hope you can see that the Win2k is much worse visually than Win7

**Comment by samdark** [comment]
Thanks for detailed report. For `5.` it could be lack of ClearType support or the way remote desktop client compresses screen image.

**Comment by jjdunn** [comment]
I don't have the "pixelated" problem using *any* other website on Win2k8R2 remote-desktop, so I doubt it's something intrinsic to remote-desktop-client.

The current font-stack for the main paragraph text is : "pt_sansregular,sans-serif;"  If I remove "pt_sansregular," leaving just "sans-serif" it looks ok on the remote-desktop system.

Looking at the page header it appears the font "pt_sansregular" is not getting loaded.  Consider supplying it on the YiiFramework.com server, or serving from a public URL ?

Finally, this point [5] about the pixelated font is actually a completely separate issue from points 1-4 of the ticket.  I should probably have opened a separate ticket for it since it's not related just to the "Search" feature....please feel free to split the ticket, or I can do so if you wish.

**Comment by samdark** [comment]
Please do so. Thanks.

**Comment by jjdunn** [comment]
point [5] of this issue has been moved to #380.  

If someone knows how and has permission, please remove point [5] from the ticket description.  I cannot see how to edit the original ticket...

**Comment by cebe** [comment]
> there is no valid reason to require the class-name, or "." or "::" prefix in order to find a method. Typing "beforeSave" should find the beforeSave() method anywhere it is implemented

>     1. there is no valid reason to require the class-name, or "." or "::" prefix in order to find a method.  Typing "beforeSave" should find the beforeSave() method anywhere it is implemented

fixed by 7340532

**Comment by cebe** [comment]
>     2\. there is no way to find class Properties in the Search box now;  but I think they used to be available.  Try searching for "scenario" and it shows nothing; but the "scenario" property exists in CActiveRecord (v1.1).  Please add/restore this feature.

CActiveRecord::$scenarios is a magic property, it is induced by getters and setters. I have enabled the search to look for `getScenario` and  `setScenario` when typing `scenario`. This should fix this case.

**Comment by jjdunn** [comment]
thank you !  the search improvements are working and very welcome :-)
