### ISSUE TITLE
Password recovery is not working

### ISSUE THREAD

**Issue by FabrizioCaldarelli** [yiisoft-contrib/yiiframework.com#381]
I've requested password recovery using this page:

https://www.yiiframework.com/login

After submit, I read the flash message "Check your email for further instructions." at top, but I've not received any email from Yii2 website to recover my password.

**Comment by cebe** [comment]
please send an email via the contact form, include your email and username: https://www.yiiframework.com/contact

**Comment by cebe** [comment]
I could not answer to your email as gmail is blocking my answer too. Find a copy below:

---

Hi,

it looks like google is blocking our mails to your account because they
are considered SPAM.

E-Mail was working fine for gmail before, do you have configured
stricter rules for your account?

best regards,
Carsten

**Comment by cebe** [comment]
I have added yiiframework.com to google postmaster tools to get more insight on this. At the moment there is no data shown there, so we need to wait a bit.

**Comment by FabrizioCaldarelli** [comment]
Thanks, now it is working.

**Comment by FabrizioCaldarelli** [comment]
But I've tried to replace old password and I receive a Database Exception

**Comment by cebe** [comment]
does this still happen? I believe I fixed that issue a few minutes ago.

**Comment by FabrizioCaldarelli** [comment]
Yes, this still happens.

This is the url:
https://www.yiiframework.com/auth/reset-password?token=q-BkvrPOkm4TGukZzH6Ip3_wNxVWcdyD_1533682327

Output:

Database Exception (#2002)
An internal server error occurred.

**Comment by cebe** [comment]
we have some problems with the forum database. If the forum is online you should be able to reset your password.

**Comment by FabrizioCaldarelli** [comment]
@cebe Thanks, now it works.

**Comment by cebe** [comment]
solved via #84
