### ISSUE TITLE
Changing avatar on website has no effect on forum

### ISSUE THREAD

**Issue by rob006** [yiisoft-contrib/yiiframework.com#392]
About an hour ago I changed my avatar on website profile (https://www.yiiframework.com/user/profile), but on forum old avatar is still used. Is there any way to sync this change with forum? I don't see any option to change avatar on forum.

**Comment by cebe** [comment]
you may need to log out on the forum and log in again.

**Comment by cebe** [comment]
Will check if there is a way to make this process go more smooth. related to #387

**Comment by rob006** [comment]
> you may need to log out on the forum and log in again.

Doesn't help. I also tried on fresh session in private mode.
