### ISSUE TITLE
i can not login to forum.

### ISSUE THREAD

**Issue by hermans** [yiisoft-contrib/yiiframework.com#395]
i can not login to forum, it ask me to verify my email. after press verify link i do not get email.
![email-issue](https://user-images.githubusercontent.com/938767/45275379-a5169b00-b4e6-11e8-975e-518bd7d03e3e.PNG)

**Comment by samdark** [comment]
`ysf_hermanto@***.com`?

**Comment by hermans** [comment]
I did. But i don't see in spam too

**Comment by cebe** [comment]
emails have been delivered to your mail providers server, there is nothing we can do if they get accepted but don't show up in your mailbox, sorry. :-/

**Comment by samdark** [comment]
Contact me at `sam@rmcreative.ru` and we'll solve it.
