### ISSUE TITLE
recent pdo mssql driver break getLastInsertID

### ISSUE THREAD

**Issue by int128fly** [yiisoft-contrib/yiiframework.com#402]
since https://docs.microsoft.com/en-us/sql/connect/php/pdo-lastinsertid?view=sql-server-2017 driver
yii has broken if you update the mssql driver
getLastInsertID after saving a model is always empty when not using a sequence

my temporary fix was to go into framework/db/schema/mssql/CMssqlCommandBuilder.php and added the following method

```
/** this is a temporary fix for the new sql server driver */
public function getLastInsertID($table)
{
    $this->ensureTable($table);
    if ($table->sequenceName !== null)
        return $this->getDbConnection()->getLastInsertID(null);
    else
        return null;
}
```

**Comment by cebe** [comment]
This is the wrong repo, your code seems to be related to https://github.com/yiisoft/yii
