### ISSUE TITLE
Forum should be 1-click reachable

### ISSUE THREAD

**Issue by samdark** [yiisoft-contrib/yiiframework.com#408]
Currently it requires two clicks in order to reach forum. Should a single click since forum is preferred place to ask questions in terms of reuse via Google afterwards.

**Comment by rob006** [comment]
![5283ff14](https://user-images.githubusercontent.com/5972388/50664360-16ee8500-0fad-11e9-9cff-f247c1e6a7ab.png)

**Comment by rob006** [comment]
Hide some items before hamburger-menu breakpoint?

**Comment by samdark** [comment]
That's doable but I'm not sure what items are less important now...

**Comment by rob006** [comment]
For me "Extensions" is quite useless. There are 759 registered extensions for Yii2, and on Packagist there are ~9k libraries for Yii2. Guess where I will search libraries for my Yii2 project :D.

**Comment by samdark** [comment]
Makes sense. Done.
