### ISSUE TITLE
UX and Design of new sites

### ISSUE THREAD

**Issue by bethrezen** [yiisoft-contrib/yiiframework.com#41]
I've asked my partner usability-expert for help with new UX&Design.
For the start he created [mood board](https://conceptboard.com/board/tehp-kb4t-epyb-4kcb-7gqa)(login as guest for quick look).
The goal of mood board is to pick overall stylistics of new sites. It is done for specifying the vector of UX prototyping and future design.
Note, that this is only stylistics - the final color-style will be the same as yii branded colors.
Please take a look at mood board and tell your opinion.
The next step is usability prototyping based on #40 requires a decision.

**Comment by samdark** [comment]
No progress since then. I guess there won't be any from that UX-expert.
