### ISSUE TITLE
Wording: Class Reference vs. API Documentation

### ISSUE THREAD

**Issue by cebe** [yiisoft-contrib/yiiframework.com#42]
we currently mix these two terms as synonyms a lot over the pages.
We should decide for one term to use everywhere.

**Comment by Deele** [comment]
I think, "API Documentation" is bad choice, "Class Reference" is much better, but simply "Documentation" is more universal.

Essentially, it is not an API, it is not an *programming interface*, those are just predefined PHP classes, not the whole new interface.

The API is another thing I described in #117

**Comment by cebe** [comment]
The classes, together with their public methods and properties, form the Application Programming Interface provided by the framework.

**Comment by jacmoe** [comment]
I am a programmer, and you are wrong.

*API* means *Application Programming Interface* and *API Documentation* means documentation for that thing.

https://api.jquery.com/
https://developer.here.com/documentation

The important word here is *Documentation* :)

**Comment by Deele** [comment]
I will not argue about technical terms, I'm more into the things, that newbie and learning programmers use and understand. When they talk about API - it is the thing/web service, you can CURL to and get JSON/XML response back with useful information.

It is good to educate people what API is and what it is not, but I'm only concerned about common developers that do not know *real* definitions and is just using common knowledge.

**Comment by jacmoe** [comment]
API is not only REST API.

An API is the interface exposed to *the outside world*, ie what clients (programmers) work with.  
It is irrelevant if that API is exposed through code only or over the wire via REST.

**Comment by jacmoe** [comment]
> It is good to educate people what API is and what it is not, but I'm only concerned about common developers that do not know real definitions and is just using common knowledge.

I think that most of the newbies will use the Guide, not the API docs. The API docs is for advanced users, IMO.

**Comment by Deele** [comment]
When I were starting with Yii couple years ago, I extensively used [Class Reference](http://www.yiiframework.com/doc/api/) and I remembered it like that. It felt OK and "api" keywords, that appear anywhere there did not relate to me at all.

This is one of those cases, where some research needs to be done, some poll with possible alternatives.

**Comment by jacmoe** [comment]
I just performed a search and it appears to me that almost all of the sites that use the word *Class Reference* use links that ends with *api*.  
API is actually more accurate because an interface is more than just classes. :)

**Comment by Deele** [comment]
As [I stated previously](https://github.com/yiisoft-contrib/yiiframework.com/issues/42#issuecomment-173720952), I'm voting for "Documentation", not "Class Reference", to avoid any misunderstandings.

**Comment by jacmoe** [comment]
The Documentation is split into two discrete parts: Guide and API.

If it wasn't split in two parts, it would have been named *Documentation*, obviously. :)

**Comment by Deele** [comment]
I would not add guide as second level of documentation, because, it is just the guide.

And in documentation, second level should already be namespaces.

**Comment by jacmoe** [comment]
The Guide is a first class member of *Documentation* - probably the most important piece of documentation that Yii has got.

**Comment by jacmoe** [comment]
> I would not add guide as second level of documentation, because, it is just the guide.
> And in documentation, second level should already be namespaces.

Make sure that you are referring to http://yiiframework.domain-na.me/ and not current site.
