### ISSUE TITLE
Search API error in console

### ISSUE THREAD

**Issue by samdark** [yiisoft-contrib/yiiframework.com#422]
![pasted_image_at_2019-01-26__12_10_am](https://user-images.githubusercontent.com/47294/51792881-cc85b000-21c8-11e9-8267-4a6334b09ffd.png)

**Comment by cebe** [comment]
could you show the end of the response payload? is it possible that it is truncated?

**Comment by machour** [comment]
Seems to be a Firefox network tab bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1319749
Copying the request as cURL and executing in the terminal gives a valid JSON here.
