### ISSUE TITLE
Enhance the website menu layout on forum

### ISSUE THREAD

**Issue by machour** [yiisoft-contrib/yiiframework.com#425]
As soon as the window height is < 1100px, the menu start eating up a lot of the screen:

![screen shot 2019-01-30 at 1 55 30 pm](https://user-images.githubusercontent.com/304450/51982655-e4925380-2496-11e9-8799-e63e6d29320e.png)

**Comment by machour** [comment]
@cebe @samdark how can I work on this? Is the configuration/css/js used on forum.yiiframework.com available somewhere to fiddle with?

**Comment by cebe** [comment]
AdminController renders some html that can be added to discourse in discourse configuration:

https://github.com/yiisoft-contrib/yiiframework.com/blob/7bd81cf2d90e2d40a462e2d58eeae8d632155c8c/controllers/AdminController.php#L70

so if you go to admin in your local install of yiiframework.com you should be able to access this.

Let me know if you need more input.
