### ISSUE TITLE
extra square brackets injected into SQL server queries

### ISSUE THREAD

**Issue by raymond1** [yiisoft-contrib/yiiframework.com#435]
Yii does not work with SQL server containing more than one space in the name, such as [PPPPPPPP$Internet Customer Cart]. Try setting up a hasMany relation between two tables where both tables have two spaces in the name. There will be an error.

**Comment by samdark** [comment]
Please report to https://github.com/yiisoft/yii2/issues. This repository is about yiiframework.com website only. Thanks.
