### ISSUE TITLE
Use Yiipowered.com for the front page

### ISSUE THREAD

**Issue by samdark** [yiisoft-contrib/yiiframework.com#449]
https://forum.yiiframework.com/t/suggestion-add-yiipowered-com-link-in-header-or-footer-of-yiiframework-com/126480

**Comment by samdark** [comment]
API is available: https://yiipowered.com/en/api/1.0

**Comment by SOHELAHMED7** [comment]
Hi @samdark, I am willing to help resolve this issue, can you please share where you would like to add link?

**Comment by samdark** [comment]
I'm thinking about fetching top 5 once a week using cron and including them at the front page. But other suggestions are welcome.

**Comment by SOHELAHMED7** [comment]
Yes, that is good idea. Also this made me suggest to have "They Help Us Make Symfony" section like in https://symfony.com/. I think this encourages contributors.

**Comment by samdark** [comment]
@SOHELAHMED7 you mean bottom https://www.yiiframework.com/team?

**Comment by samdark** [comment]
![image](https://user-images.githubusercontent.com/47294/60247421-509fa900-98c9-11e9-987a-0b15ca4f4b28.png)

Here's current link to YiiPowered btw.

**Comment by SOHELAHMED7** [comment]
> you mean bottom https://www.yiiframework.com/team?
let that there as it is

I am suggesting to add a section in global footer or footer of home page which contain random contributor who committed at least one commit to Yii, like that of Symfony

**Comment by samdark** [comment]
I'm fine with it but it's a separate thing from this issue :)

**Comment by SOHELAHMED7** [comment]
> I'm fine with it but it's a separate thing from this issue :)

added https://github.com/yiisoft-contrib/yiiframework.com/issues/450


This issue can be closed.
