### ISSUE TITLE
Password login / change password forms are missing rate limiting

### ISSUE THREAD

**Issue by samdark** [yiisoft-contrib/yiiframework.com#459]
Both forms are missing rate limiting. That allows brute-forcing (not very efficiently but still...) login and then brute-forcing password reset.

Rate limiting should be added to these endpoints.

**Comment by cebe** [comment]
This is currently being abused by spammers... :-(

https://github.com/yiisoft-contrib/yiiframework.com/blob/dfe6f1360139507c10832d328b02451a96cc9e37/controllers/AuthController.php#L190-L213

**Comment by samdark** [comment]
Rate-limited /login, /signup and /auth/password-reset via Nginx config. Now these give you 503 if you do more than 1 request per second.
