### ISSUE TITLE
Redirect urls with trailing slashes

### ISSUE THREAD

**Issue by cebe** [yiisoft-contrib/yiiframework.com#46]
Urls on current framework site are ending with `/`, e.g. http://www.yiiframework.com/doc/api/
To allow these to be handled by the new site we need to introduce a redirect from URL with slash to URL without slash.

see also: 
- https://github.com/yiisoft/yii2/issues/7670
- https://github.com/yiisoft/yii2/issues/8370
- https://github.com/qiangxue/yiiframework.com/blob/master/config/urls.php#L22

**Comment by cebe** [comment]
see my comments: https://github.com/yiisoft-contrib/yiiframework.com/commit/2520408d34dea3919e2e4043e93fb14870c86062#commitcomment-15235794

**Comment by cebe** [comment]
does not work: http://yiiframework.domain-na.me/doc/api/2.0/ <- http 404
can you look into it?

**Comment by samdark** [comment]
Yes.
