### ISSUE TITLE
dropdown menu on 320

### ISSUE THREAD

**Issue by Arhell** [yiisoft-contrib/yiiframework.com#461]
found a bug on the 320 screen and fixed it
Before:
![1](https://user-images.githubusercontent.com/26163841/74614924-c5f40e80-5124-11ea-9bc3-c0d8d3304e23.jpg)
After: 
![2](https://user-images.githubusercontent.com/26163841/74614933-cee4e000-5124-11ea-9186-c50077d5db22.jpg)
pull [link ](https://github.com/yiisoft-contrib/yiiframework.com/pull/462)

**Comment by samdark** [comment]
After building it, it did not end up in CSS. Should be re-checked.

**Comment by samdark** [comment]
https://github.com/yiisoft-contrib/yiiframework.com/commit/ab477594f90ef493fc3cab5cf58bdc17bbc3281b nailed it.

**Comment by samdark** [comment]
Thank you, @Arhell
