### ISSUE TITLE
Keep track of old content

### ISSUE THREAD

**Issue by cebe** [yiisoft-contrib/yiiframework.com#50]
This is to track old content that will be kept on the new site and possibly necessary redirects.

| old | new | status |
| --- | --- | --- |
| `/about/` About Yii | `/about` and `/team` | :white_check_mark:  https://github.com/yiisoft-contrib/yiiframework.com/issues/50#issuecomment-167760048 |
| `/features/` | redirect to front page | :white_check_mark: #5 |
| `/performance/` | redirect to front page | :white_check_mark: |
| `/license/` | `/license` | :white_check_mark: |
| `/contact/` | `/contact` | :white_check_mark: |
| `/download/` | `/download` | :white_check_mark: |
| `/extensions/*` | `/extensions` | :white_check_mark: #15 |
| `/demos/` | redirect to front page | :white_check_mark: |
| `/logo/` | `/logo/` | :white_check_mark:  logo itself should be adjusted (remove shadow) |
| `/doc/` | `/books` | :white_check_mark: (no need for a redirect but `/doc` should point somewhere) |
| `/tour/` | "Getting started" link | :ballot_box_with_check:  #49 draft version done, need improvements |
| `/tutorials/` | Redirect to `/resources` | :white_check_mark:  |
| `/doc/api/*` | `/doc/api/*` | :white_check_mark: (#34) |
| `/doc/guide/*` | `/doc/guide/*` | :white_check_mark: (#33) |
| `/doc/blog/*` | linked from ressources now, url is same | :white_check_mark:  (#32) |
| `/doc-2.0/*` | redirect to `/doc/*` | :white_check_mark: |
| `/wiki/*` | `/wiki` | :white_check_mark: #16 |
| `/screencasts/` | Redirect to `/resources`  | :white_check_mark: |
| `/resources/` | `/resources` | :white_check_mark: |
| `/contribute/` | `/contribute` | :white_check_mark: |
| `/security/` | `/security` | :white_check_mark: |
| `/forum/*` | should stay as is | :ballot_box_with_check: #84 |
| `/chat/` | `/chat` | :white_check_mark: |
| `/community/` | `/community` | :white_check_mark: |
| `/news/` | `/news` | :white_check_mark: (#47) |
| `/user/*` | `/user/*`  | :white_check_mark: |
| `/user/halloffame/` | `/user/halloffame` | :white_check_mark:  |
| `/badges/` | `/badges` | :white_check_mark:  |
| `/tos/` | `/tos` | :white_check_mark: (#48) |
| `/rss.xml/` | /rss.xml | :white_check_mark: |

**Comment by jacmoe** [comment]
I took the liberty of removing the 'about' page because there already is a page about Yii in the Guide.
The navbar points to that page in the guide instead.
If that is acceptable, then a redirect is needed.

**Comment by samdark** [comment]
Redirects are handled in code.

**Comment by cebe** [comment]
there are files under http://www.yiiframework.com/files/ e.g. http://www.yiiframework.com/files/CHANGELOG-1.1.16.txt

**Comment by samdark** [comment]
I don't think we need old changelogs.

**Comment by samdark** [comment]
Maybe for history it worth archiving and keeping in a backup somewhere.

**Comment by cebe** [comment]
http://www.yiiframework.com/site/markdownHelp/

**Comment by samdark** [comment]
I've re-checked everything from original list. Most of pages are now in place or redirect to appropriate replacements. What's left:

## http://www.yiiframework.com/community

Not sure what to do with it. We [have a good list here](https://github.com/yiisoft/yii2/wiki/communities) but even if we'll do the same at the website, it's not clear from where to link to it.

## Archive / history

I'd not put any of that at the website. Instead, it worth creating `yiisoft/history` at GitHub and pushing historical stuff there.

## Markdown help

Is it used anywhere?

**Comment by cebe** [comment]
> I'd not put any of that at the website. Instead, it worth creating yiisoft/history at GitHub and pushing historical stuff there.

why?

> Markdown help

probably not needed, there are a lot of resource on markdown on the web.

**Comment by cebe** [comment]
> Not sure what to do with it. We have a good list here but even if we'll do the same at the website, it's not clear from where to link to it.

could be an additional point in the "Community" nav dropdown, e.g. "External/Other resources" or something like that.

**Comment by samdark** [comment]
I prefer keeping it off-site because it doesn't worth the effort. There are probably one or two people in community who are interested in 1.0 pre-release versions... Creating GitHub repo is easy and safe for the purpose.

I'll handle these additional resources page.

**Comment by samdark** [comment]
https://github.com/yiisoft-contrib/museum

**Comment by samdark** [comment]
https://github.com/yiisoft-contrib/yiiframework.com/commit/fefd73b36207adb350ae1efabd13eefe599661d5
