### ISSUE TITLE
extension docs are not updated

### ISSUE THREAD

**Issue by cebe** [yiisoft-contrib/yiiframework.com#500]
https://www.yiiframework.com/extension/yiisoft/yii2-app-advanced/doc/guide/2.0/en/start-installation

shoud be updated automatiacally from 

https://github.com/yiisoft/yii2-app-advanced/blob/master/docs/guide/start-installation.md

 but it does not seem to work.

**Comment by samdark** [comment]
Seems to be still valid.

**Comment by arogachev** [comment]
Yes. Found the root of the problem. Fixed in https://github.com/yiisoft-contrib/yiiframework.com/pull/974/commits/8bce463cf0053c2ca5a61ab9f1d6b5473dcd59e4.
