### ISSUE TITLE
Get rid of `word-break: break-all`

### ISSUE THREAD

**Issue by rob006** [yiisoft-contrib/yiiframework.com#502]
I suggest to replace all recent additions of `word-break: break-all` (it creates issues like https://github.com/yiisoft-contrib/yiiframework.com/pull/498#issuecomment-607714590) by some generic `word-break: break-word;` added to body. `break-word` will break words only if it is absolutely necessary (the word does not fit on the screen) and should fix https://github.com/yiisoft-contrib/yiiframework.com/issues/497 and similar errors.

**Comment by Arhell** [comment]
@rob006  I also propose to use this only on mobile <767

**Comment by rob006** [comment]
> I also propose to use this only on mobile <767

Why? If word/link is long enough, it could overflow on any vieport. I don't see a reason to make an exception for >=767px.

**Comment by samdark** [comment]
I agree. It proved to behave badly. We should not hard-break words in between.

**Comment by rob006** [comment]
This problem still exists in API: https://www.yiiframework.com/doc/api/2.0/yii-i18n-i18n

![495595b6](https://user-images.githubusercontent.com/5972388/98395367-72cc3e00-205c-11eb-971e-ec3e1d47045a.png)

**Comment by samdark** [comment]
@Arhell would you please check it?

**Comment by Arhell** [comment]
sure
