### ISSUE TITLE
dropdown window goes beyond

### ISSUE THREAD

**Issue by Arhell** [yiisoft-contrib/yiiframework.com#514]
![c4f2761871](https://user-images.githubusercontent.com/26163841/80038556-8ec42400-84fe-11ea-9d3b-2a7d876cd717.jpg)
last item

**Comment by samdark** [comment]
It is better now. But there are still issues.


Left menu is trimmed:

![image](https://user-images.githubusercontent.com/47294/80358968-dbed2080-8885-11ea-8a2d-e0d45cc28db0.png)

Right menu is a bit mis-aligned.

![image](https://user-images.githubusercontent.com/47294/80358985-e14a6b00-8885-11ea-80ed-8e613bc5d0b2.png)
