### ISSUE TITLE
fix search results on mobile

### ISSUE THREAD

**Issue by Arhell** [yiisoft-contrib/yiiframework.com#521]
![2](https://user-images.githubusercontent.com/26163841/80926424-dc168000-8d9f-11ea-8674-119d5dbf03e4.jpg)

**Comment by samdark** [comment]
![image](https://user-images.githubusercontent.com/47294/81188195-b2d33b00-8fbd-11ea-879c-98e2e32cacbd.png)

Results are now trimmed on mobile.
