### ISSUE TITLE
Forgot password does not work

### ISSUE THREAD

**Issue by SOHELAHMED7** [yiisoft-contrib/yiiframework.com#528]
Forgot password feature does not work

Steps:

1. Visit https://www.yiiframework.com/auth/request-password-reset
2. Enter email
3. You will get link to reset password
4. Enter new password 
5. Enter new password again
6. Submit the form. 

It will keep loading. No any result is shown. Password reset is sucessfull or not?

It should give some valid response. Success or failure.

Also I cannot login if my password is not reset. 

This is critical bug

I think it is related to mail configuration

**Comment by samdark** [comment]
@cebe would you please look into it? The code should be alright.

**Comment by SOHELAHMED7** [comment]
I recently tried to reset password, and it all worked perfect. Should this issue should be closed ?

**Comment by samdark** [comment]
Yes.
