### ISSUE TITLE
Hello world

### ISSUE THREAD

**Issue by jacmoe** [yiisoft-contrib/yiiframework.com#53]
I have forked and created a branch entitled 'yiimock' where I have switched the build toolset from Grunt to Gulp and converted the Less files to Sass.
It works with the Roxio theme just fine - and is much faster now with Gulp and even has Browsersync included.

Now, however, I am wondering what the next step would be..

I would like to start with the current layout but starting from a blank slate with regards to the stylesheets.
Will most probably be using Bootstrap 3.5.x in Sass and borrowing ideas from my mockup - hence the name of the branch.
Will merge ideas from the current theme and what I think works well from my experiment..

Or what do you think?

:)

Bootstrap 4 is using Sass and they have removed Glyphicons, so I guess it's time to move to Fontawesome..
So the move from Less to Sass is definitely warranted.
And it would be nice to move to Bootstrap 4, but that would mean that Yii Bootstrap would need an upgrade as well..

Yes, I know that I am a chatterbox.
Just wanted to introduce my intentions.

**Comment by jacmoe** [comment]
PS: I will definitely find the time to read the issues in this tracker as they seem to be full of useful 'stuff'.

And the branch in question: https://github.com/jacmoe/yiiframework.com/tree/yiimock

**Comment by samdark** [comment]
Next step is to pull request what you've done. One step a time. No giant pull requests please.

**Comment by samdark** [comment]
Closing since it's meta-issue ;)

**Comment by jacmoe** [comment]
Of course it is a meta issue! Obviously.
However, I think I am going to re-fork and organize things better so that the PRs will be tighter and more focused.

**Comment by samdark** [comment]
Thanks!
