### ISSUE TITLE
Port to Sass and Gulp

### ISSUE THREAD

**Issue by jacmoe** [yiisoft-contrib/yiiframework.com#54]
I have ported the build script from using Grunt to using Gulp and have added Browsersync (live reload) to it.
It works great and is much faster than Grunt because Gulp uses pipes.

I have also ported the Less scripts to Sass. And the theme (Roxio) does not seem to have taken any collateral damage.
Mainly because both Less and Sass (scss) can gobble regular css quite well.

Do you want it?
I am in the process of preparing a Pull Request for this.

It would require the installation of Ruby and Sass, but since the next version of Bootstrap is powered by Sass, that would have to be done anyway.

**Comment by samdark** [comment]
Yes, we want it.

**Comment by jacmoe** [comment]
And then the next question:
I did remove Grunt script and related deps in package.json - is that acceptable?
Or do you prefer to do that yourself?
I also changed the Readme to reflect the new build script.

**Comment by samdark** [comment]
Yes, that is acceptable.

**Comment by cebe** [comment]
@jacmoe feel free to change frontend related tools as you like or feel the need to.

**Comment by jacmoe** [comment]
Thanks guys :)
Closing because it is referenced by #57
