### ISSUE TITLE
pictures are not full width

### ISSUE THREAD

**Issue by Arhell** [yiisoft-contrib/yiiframework.com#540]
![1](https://user-images.githubusercontent.com/26163841/83311078-c9fcf580-a216-11ea-8b94-5ef0dd5d2008.jpg)

**Comment by samdark** [comment]
@Arhell wouldn't the fix done scale the image making it blurry?

**Comment by samdark** [comment]
I can record produce similar animation and slides with more resolution if needed or we can try to switch to pure HTML (at the moment it was introduced to the website the size of JavaScript needed to do it was more than the size of the gif).

**Comment by samdark** [comment]
@Arhell how do you want to deal with it?

**Comment by Arhell** [comment]
@samdark 
Hi, preferably x2 images, that would be good on the retina.
It’s better to redo them, that is, to take new screenshots, the rest is up to me
