### ISSUE TITLE
text goes beyond the borders of the screen

### ISSUE THREAD

**Issue by Arhell** [yiisoft-contrib/yiiframework.com#548]
https://www.yiiframework.com/doc/api/2.0/yii-console-controllers-basemigratecontroller
![1](https://user-images.githubusercontent.com/26163841/84441973-6b3b7100-ac45-11ea-9981-98e7f45a58c9.jpg)

**Comment by samdark** [comment]
break-word is not a good fix. Let's not use it:

![image](https://user-images.githubusercontent.com/47294/84624709-91ce0600-aeea-11ea-9fb1-e0b597214711.png)

**Comment by samdark** [comment]
https://github.com/yiisoft-contrib/yiiframework.com/commit/755da93b312e49ae47e7fa9bad65ebcfd56250c7
