### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by Arhell** [yiisoft-contrib/yiiframework.com#568]
https://www.yiiframework.com/books
![1](https://user-images.githubusercontent.com/26163841/87241912-5b73a000-c430-11ea-86a4-74791fc0cf38.jpg)

**Comment by samdark** [comment]
- Yii Rapid Application Development: https://www.amazon.com/Yii-Rapid-Application-Development-Hotshot/dp/1849517509
- Web Application Development with Yii and PHP: https://www.amazon.com/Web-Application-Development-Yii-PHP/dp/1849518726
