### ISSUE TITLE
"make docs" command is failing on PHP 7.2 when installing the project

### ISSUE THREAD

**Issue by SOHELAHMED7** [yiisoft-contrib/yiiframework.com#571]
CLI - PHP version 7.2.

I am trying to install and set up this project to run locally as I am trying fix https://github.com/yiisoft/yii2-apidoc/issues/197

I am following steps provided at readme - https://github.com/yiisoft-contrib/yiiframework.com#installation 

Everything works fine till `make docs` command

Command `make docs` fails giving error

```
Processing files... 88% (385/434) ETA: 3 sec.   PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in /path/to/yiiframework.com/data/yii-2.0/framework/base/Object.php on line 28
Exception 'phpDocumentor\Reflection\Exception\UnparsableFile' with message 'The given file could not be interpreted as it contains errors: Errors parsing /path/to/yiiframework.com/data/yii-2.0/framework/base/Object.php'

in /path/to/yiiframework.com/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/FileReflector.php:130
```

### Expected result

Command should run with out error

**Comment by samdark** [comment]
What PHP version do you use?

**Comment by samdark** [comment]
Should be OK now. Do `composer update` locally.

**Comment by SOHELAHMED7** [comment]
Status:

Did `composer update` still faced above issue.

Did pull from the upstream master and then `composer update` that solved the issue and introduced the new one:

`make docs` now give error that elastic search config is not configured. However the docs says it is not required. 

The app runs fine in my local computer but still on guide page I get 404 not found error. 

Thanks.

**Comment by samdark** [comment]
> However the docs says it is not required.

**Comment by SOHELAHMED7** [comment]
#### Elastic search error

`$ ./yii search/rebuild api`


Exception 'yii\elasticsearch\Exception' with message 'Elasticsearch request failed: 7 - Failed to connect to 127.0.0.1 port 9200: Connection refused'

in /path/to/yiiframework.com/vendor/yiisoft/yii2-elasticsearch/Connection.php:516

Error Info:
```
Array
(
    [requestMethod] => GET
    [requestUrl] => http://127.0.0.1:9200/_nodes/_all/http
    [requestBody] => 
    [responseHeaders] => Array
        (
        )

    [responseBody] => 
)
```

This is error I am getting because elastic search config is not set. 



Before I pulled from upstream master, I was getting same error as in issue description 

In browser at `http://localhost/yiiframework.com/web/doc/guide`, I am getting 404


```
Not Found
The requested URL was not found on this server.

Apache/2.4.43 (Ubuntu) Server at localhost Port 80
```

**Comment by SOHELAHMED7** [comment]
I do not run `$ ./yii search/rebuild api` explicitly `make docs` runs it internally

**Comment by samdark** [comment]
Yes. That seems to be incorrect info in readme.
