### ISSUE TITLE
Failed to create a new extension from Packagist

### ISSUE THREAD

**Issue by letsjump** [yiisoft-contrib/yiiframework.com#585]
While linking my new extension from Packagist, the _yiiframework.com_ site crashed and wasn't able to import all the data.

My new extension is [https://www.yiiframework.com/extension/letsjump/yii2-easy-ajax](https://www.yiiframework.com/extension/letsjump/yii2-easy-ajax) and this is the Packagist page: [https://packagist.org/packages/letsjump/yii2-easy-ajax](https://packagist.org/packages/letsjump/yii2-easy-ajax).

These are the missing data:

- the whole README.md
- license 
- yii version
- github link

`Update packagist data` or extension `update` buttons doesn't seem to fix the problem.

Thanks in advance for any suggestion

**Comment by samdark** [comment]
Seems queue wasn't running for while...

**Comment by samdark** [comment]
Will take about 5 hours to process jobs scheduled so far...

**Comment by samdark** [comment]
@cebe would you please take a look at it? We need to ensure that queue/listen is running.

**Comment by cebe** [comment]
queue service is part of monitoring now: 
![Bildschirmfoto von »2020-09-07 23-05-12«](https://user-images.githubusercontent.com/189796/92416610-a541e380-f15e-11ea-8d44-78484ea82264.png)
