### ISSUE TITLE
Correct  Git Clone Command in Readme

### ISSUE THREAD

**Issue by hscstudio** [yiisoft-contrib/yiiframework.com#59]
In follow instruction in readme (https://github.com/yiisoft-contrib/yiiframework.com/blob/master/README.md#installation)
```
# clone the project
git clone git@github.com:yiisoft-contrib/yiiframework.com.git
```
but I found error 
```
ssh_exchange_identification: read: Connection reset by peer
fatal: could not read from remote repository
```
should we use normal way to clone
```
git clone https://github.com/yiisoft-contrib/yiiframework.com.git
```
Please change, its make confuse to newbie..

Thank

**Comment by samdark** [comment]
Ideally it should be contribution guide as in main Yii repo.
