### ISSUE TITLE
Download/install page

### ISSUE THREAD

**Issue by samdark** [yiisoft-contrib/yiiframework.com#6]
Was it meant to lead to user guide or internals guide on how to develop Yii itself?

**Comment by jacmoe** [comment]
I am not sure about this page..

Like the 'About' page, the 'Download' page is in the Definitive Guide.

How about removing the pages and make the menu entries link to the guide?

That way, duplicate content could be removed, and - because the guide is editable via Github - people will be able to help us improve them via PRs.

**Comment by jacmoe** [comment]
Because in the guide, there are instructions for installing Yii - via Composer and from an archive.
I am not exactly sure how to write a separate page about this without duplicating content.
Separate pages also increases the likelihood of introducing conflicting instructions.

**Comment by cebe** [comment]
Download page should be a summary of all download options, e.g. guide docs/pdf, framework zip files etc. and should link to installation instructions from the guide.

**Comment by jacmoe** [comment]
OK. :)

I think the button on the front should go to the guide - install page instead of the download page ?

**Comment by cebe** [comment]
Yes, I think so, composer is the preferred install way anyway so download can be more hidden.

**Comment by samdark** [comment]
https://github.com/yiisoft-contrib/yiiframework.com/issues/14

**Comment by samdark** [comment]
What should be on download page? http://yiiframework.domain-na.me/download is definitely not everything we need there?

Need to define blocks for @eshill.

**Comment by cebe** [comment]
I have added some more content to the download page but its not done yet. b6a28ef81b4ef9c72a08b1fb4b384e61fc9bca62
Will add more later.

**Comment by cebe** [comment]
most of the content is there, the rest (Archive section) can be done after launsh.
