### ISSUE TITLE
Links to Bootstrap documentation go to wrong place on Class yii\bootstrap\Nav page

### ISSUE THREAD

**Issue by MacroMan** [yiisoft-contrib/yiiframework.com#600]
The links to the dropdowns and nav Bootstrap documentation on the following page (near the top, see screenshot) go to the Alerts documentation.

https://www.yiiframework.com/extension/yiisoft/yii2-bootstrap/doc/api/2.0/yii-bootstrap-nav

The links should go to https://getbootstrap.com/docs/4.5/components/dropdowns/ and https://getbootstrap.com/docs/4.5/components/navbar/ respectively.

![Screenshot from 2020-08-19 10-25-26](https://user-images.githubusercontent.com/1306658/90617312-717e3880-e206-11ea-91e8-b968ea99f7c1.png)

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2-bootstrap/commit/66c41917b90f5d8b4c14c93fbc63b7363d9d235a
