### ISSUE TITLE
Rebranding

### ISSUE THREAD

**Issue by jacmoe** [yiisoft-contrib/yiiframework.com#61]
As you know, I did a Yii mockup some days ago, and because I couldn't find the Yii font, I made a logo using the Philosopher font:
![yiismall](https://cloud.githubusercontent.com/assets/85424/11335504/f86ae78c-91dc-11e5-88d2-659c0f1089ee.png)
![yiilogo](https://cloud.githubusercontent.com/assets/85424/11335509/fd7ba5b8-91dc-11e5-8e43-7570ff77d040.png)

I think that the font makes 'Yii' stand out a lot more than what currently is the official logo.

Using a real font would also mean that the only thing that needs to be loaded is the image so it is easier to create different sizes/colors.

I haven't made a blue font grey font test, but I guess you get the idea.. :)

Using the above font also means that it is very easy to apply the Yii-font on header elements, etc..

Of course you are attached to the current logo, but I hope that you would at least consider the idea.

Note: the above logo is made using ~~CSS~~ HTML only. The logo image (clover) is embedded in the ~~CSS~~ image tag by a base64 string.

**Comment by jacmoe** [comment]
Also my suggestion also means that 'Yii' be white and not blue.
To make it stand out, of course. ;)

**Comment by jacmoe** [comment]
Here is an example of how using that font in headers helps promote the Yii look:
![yiilogo1](https://cloud.githubusercontent.com/assets/85424/11335624/1a9b83e2-91de-11e5-836c-1d9ba2336173.png)

**Comment by jacmoe** [comment]
I think that font is great because I like how Y and I looks, especially together..

**Comment by jacmoe** [comment]
Just for kicks, here's blue and grey:
![yiilogo3](https://cloud.githubusercontent.com/assets/85424/11335842/50ed0fb8-91e0-11e5-8056-2d6b09949d66.png)

**Comment by samdark** [comment]
Interesting attempt. I'd wait for more logos.

**Comment by jacmoe** [comment]
It is incredibly easy to put the proposed logo on a dark background:

Simply make 'Yii' white and 'framework' blue :)

Does the current official Yii font have a name, and where can we get it?

**Comment by cebe** [comment]
> using the Philosopher font:

Am I correct that this is a free/open font?

The new style looks cool, especially the fact that the whole site could be branded with it.

However putting the blue text on a blue background does not seem like a good idea to me :)

**Comment by jacmoe** [comment]
It is a libre font: http://www.dafont.com/philosopher.font
Using the SIL Open Font License:
http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL


2015-11-23 14:17 GMT+01:00 Carsten Brandt <notifications@github.com>:

**Comment by jacmoe** [comment]
It is a Russian font.
Very befitting, I think. :)

2015-11-23 14:21 GMT+01:00 Jacob Moen <jacmoe.dk@gmail.com>:

**Comment by cebe** [comment]
> Does the current official Yii font have a name, and where can we get it?

Not sure it has, maybe @qiangxue knows.

**Comment by mdomba** [comment]
Here is the post where the logo was introduced, the first post has the yii_logo.ai file inside the ZIP... can the font be seen from adobe illustrator?

Also here is one suggestion for the font - http://www.yiiframework.com/forum/index.php/topic/18972-yii-font/

**Comment by jacmoe** [comment]
Neo Tech does not seem to be free.


I think that Philosopher has more 'edge' to it. :)

2015-11-23 14:54 GMT+01:00 Maurizio Domba Cerin <notifications@github.com>:

**Comment by jacmoe** [comment]
We still keep the wonderful Yii petals, of course. Only a different font.

**Comment by cebe** [comment]
I am all for using a free font.

**Comment by mdomba** [comment]
I was just trying to find which one is the current font, but agree on the free font.

**Comment by jacmoe** [comment]
I managed to convert the Yii petals to a svg - will add it to the repository.
That would mean that the same 'image' can be used for all the things.

**Comment by cebe** [comment]
nice!

**Comment by hscstudio** [comment]
I propose new logo of yii
![logo of yii](http://www.hafidmukhlasin.com/wp-content/uploads/2015/11/yii-logos.png)

http://www.hafidmukhlasin.com/2015/11/24/yii2-rebranding-yii-framework-logo/

**Comment by SilverFire** [comment]
Hm. For now I like the old logo more than new one.

**Comment by cebe** [comment]
@hscstudio thanks for the proposal but we were discussing to keep the old logo but only change the font.

**Comment by samdark** [comment]
Well, if you have free time to burn it's OK to post new logos here as well. Who knows...

**Comment by jacmoe** [comment]
I like the 3 colour petals a lot, and it has always been about the font :p

The petals is part of the Yii brand, so that's probably not going to change.
Unless something outrageously great turns up.

Back in the old days, people were still using images for icons and menus, and logos :)
Now you can do all the things with CSS and fonts.

**Comment by muhammadcahya** [comment]
** Is it permissible also for the new logo here, or should create new section about 'rebranding' ?

I some idea, What do you think about that?

![yii](https://cloud.githubusercontent.com/assets/4241620/11375960/b180aeb2-9310-11e5-88fa-4f1eeff60ee4.jpg)

I think it's better to design using flat colors, although it is possible to provide shadow or gradation.

My idea is about the '*mascot*'
---
* Like cakephp with the '*cake*'
* Phalcon with '*falcon*'
* CodeIgniter with '*fire*'
* Zend with '*elephant*' (ah if it was the mascot of php or zend: p)
etc

If Yii is pronounced as Yee or [ji:], and is an acronym for "Yes It Is!"
I added about similarities mention, such as '**Yii**' and 'FL[**YI**]NG', so anything that can fly, and I see from the logo now, and I had the idea to add a 'bird's beak' in the logo.

And when I saw the logo on Dribbble, I get inspired about 'humming bird' mascot

![yiiframework](https://cloud.githubusercontent.com/assets/4241620/11375984/cc1b7ef0-9310-11e5-85c1-7b2c1d8016ec.jpg)

For font i use is Josefin Sans (Sans Serif), i chose this because is Not Mainstream (I Think), have Open Font License, and google font
I think we must chose 'serif' or 'sans serif' to our font

What's your opinion ?

**Comment by jacmoe** [comment]
I think it would be a mistake to discontinue the Yii petals that we currently have as it is a very strong brand. :)
It is also used everywhere.

Your logo looks great, and it is a good idea, but I am not sure..
Maybe use the 3 Yii colours?
$yii-yellow: #DF6E35;
$yii-blue: #3379B2;
$yii-green: #8CBC4C;

**Comment by jacmoe** [comment]
Just wanted to mention the obvious side-effect from using a real font for the logo:
Search engines.
It is better to have 'Yiiframework' wrapped in a h1 than embedded in an image, IMO.

**Comment by samdark** [comment]
Not a big difference. Search engines are fine w/:

```php
<h1><img src="..." alt="yii framework"></h1>
```

**Comment by jacmoe** [comment]
Yeah - my bad :)

2015-11-25 20:00 GMT+01:00 Alexander Makarov <notifications@github.com>:

**Comment by cebe** [comment]
@muhammadcahya thanks for your proposal! It acually took me some time to realize that there is a bird :) could be maybe more obvious :) In general I am for keeping the Yii petals. But I am not against modernizing them in some way.

**Comment by samdark** [comment]
@muhammadcahya the font is nice.

**Comment by egorio** [comment]
@jacmoe, I like the bird more than current "sanitary napkin".

But there are 2 problems - bird should fly in the [opposite direction](https://www.google.com/search?q=matrix+of+emotions&tbm=isch) (for now it flies out of Yii Framework), and bird is [Falcon's](https://phalconphp.com/) logo.

For me, current logo looks old :(

**Comment by jacmoe** [comment]
I don't agree:
![yii_petals](https://cloud.githubusercontent.com/assets/85424/11407777/2f531a38-93b5-11e5-8596-1e998fd01461.png)

**Comment by jacmoe** [comment]
That is the svg-based and cleaned up logo, btw.

**Comment by egorio** [comment]
And... guys. Did you think about color blindness? How do you think [people with color blindness](https://en.wikipedia.org/wiki/Color_blindness#Epidemiology) see your beautiful graded color logo? Or you don't interested in them?

**Comment by jacmoe** [comment]
I think you are being a bit too agressive @egorio ..
No, I don't care much about how color blind people view the logo because it is not important for a logo.
Not too bad in the color blind simulator here: http://www.color-blindness.com/coblis-color-blindness-simulator/

**Comment by jacmoe** [comment]
I found the font Tenby five which is pretty close to the proprietary Neo Tech:
![yiilogo5](https://cloud.githubusercontent.com/assets/85424/11409300/3c816340-93bf-11e5-842b-cbccaacd8fd8.png)
I am not too fond of that style, but if you are not keen on change, then that could be a suitable replacement. :)

http://www.fontsquirrel.com/fonts/Tenby-Five

**Comment by egorio** [comment]
@jacmoe, I'm sorry if I seemed aggressive ;) 
About "it still..." I meant "yes, it's true", but format and crystal clear are not the point of logo.

I just wanted to show my point - the logo is not so good and I think if you think about rebranding, let's think about new (modified) logo.

And I like the font "Tenby Five" above :) But "yiiframework", "yii framework" or "Yii Framework"?

**Comment by jacmoe** [comment]
Tenby Five has an ugly looking capital Y I am afraid..
![yiilogo6](https://cloud.githubusercontent.com/assets/85424/11409497/b287234e-93c0-11e5-815c-866cfbe2e231.png)

**Comment by jacmoe** [comment]
It could grow on me, though..

The Y kind of looks like a fork - Poseidon's trident?

**Comment by jacmoe** [comment]
However, I still think that Philosopher has more edge to it:
![yiilogo7](https://cloud.githubusercontent.com/assets/85424/11409645/9d865392-93c1-11e5-949a-bbcd726f34a8.png)
http://www.dafont.com/philosopher.font?text=Yii+Framework

**Comment by jacmoe** [comment]
Just want to stress that my motivation for opening up this issue was solely to change the font used, not the logo itself.
But, of course, if there is to be a radically cool new logo to arrive on the scene, then I guess we would have to reconsider. :)

**Comment by egorio** [comment]
Font looks cool :) 
But "ii" like 2 zombies go to Y for me :)

**Comment by jacmoe** [comment]
Now I can never unsee that @egorio ! :dancers:

**Comment by jacmoe** [comment]
This is a test using Tenby:
![yiilogo8](https://cloud.githubusercontent.com/assets/85424/11410270/52123b60-93c6-11e5-8ccb-09e2a84c57f5.png)

**Comment by jacmoe** [comment]
Un-bolded and with darker 'framework':
![yiilogo9](https://cloud.githubusercontent.com/assets/85424/11410338/f2bc6c52-93c6-11e5-80d4-6bdb47190089.png)

**Comment by jacmoe** [comment]
And - before I stop spamming this issue - here is how it looks if using Tenby regular for the content:
![yiilogo10](https://cloud.githubusercontent.com/assets/85424/11410465/e28278a8-93c7-11e5-86d4-d6ae9e0f1e2c.png)

**Comment by jacmoe** [comment]
I added Tenby Five in #71 so that we can test it.
Here's how it looks when Tenby is used for the headers:
![yiilogo11](https://cloud.githubusercontent.com/assets/85424/11411551/5215bc08-93d1-11e5-9d66-5b499e2dab13.png)

**Comment by egorio** [comment]
Here are some ideas about logo, if you decide to update it.
![img_0495](https://cloud.githubusercontent.com/assets/1502496/11412234/1220e3c6-938f-11e5-88af-f0177d7a19f6.JPG)

**Comment by samdark** [comment]
Second row, third column looks interesting.

**Comment by muhammadcahya** [comment]
>I think it would be a mistake to discontinue the Yii petals that we currently have as it is a very strong brand. :)
It is also used everywhere.

@jacmoe , Previously I put respect for @qiangxue for the best current logo, yes I know it's a very strong and this brand is used everywhere, but I do not say it '**Should be**' or '**Must**' (*to change current logo*), but we're talking here about '**Rebranding**' you know.

I will try to help if necessary change the logo to more fresh, and more modern, but I also would willingly because I agree with your thoughts, because 'current logo' has been very good to me, @qiangxue has create a brandly logo :)
So actually nothing to lose for me whether it should change the logo or retain the current logo, my previous post just trying to give some ideas and opinions only. For 3 colors did before I thought about it, but maybe I will use the new hexa color, and compared with the previous.

---

Thank's @cebe & @samdark , Honestly I made this logo as a 3 petals (in previous logo I'm trying to create '*new petals*' from current yii logo), but maybe you do not see it, or it may even look like a leaf? Hahaha

---
>But there are 2 problems - bird should fly in the opposite direction (for now it flies out of Yii Framework), and bird is Phalcon's logo.

@egorio for me current logo is best too :), for opposite direction yes I think same with you and I'm agree, my previous logo is inspiring from current logo for now it flies out of Yii Framework too, you know, and about phalcon logo I do not think about the same logo with Phalcon, One thing the same is about bird, but my purpose is not to look for it, but on the idea that as I described earlier.

And thanks for your ideas about logo

**Comment by jacmoe** [comment]
This is how it looked five years ago:
![logo](https://cloud.githubusercontent.com/assets/85424/11412565/939ab63a-93de-11e5-8000-ea7ec6fe190a.gif)
:P

**Comment by jacmoe** [comment]
The current logo was made by a professional designer and the goal was to not make the colours too bright, while at the same time creating a strong identity. The shape is organic and flower-like.

I like the ideas from @egorio and would like to see them in the Yii colours. :)

**Comment by jacmoe** [comment]
@muhammadcahya Please, bring it on! I didn't mean to put any dampers on your creativity :)

**Comment by hscstudio** [comment]
I think font selected by @muhammadcahya very briliant, with elegant & modern color and not mainstream.. its look great.. but please improve Your logo..

**Comment by muhammadcahya** [comment]
@hscstudio Oke suhu :)
How about this, what's your opinion :
![yiiframework](https://cloud.githubusercontent.com/assets/4241620/11414851/3f77a730-942d-11e5-90bf-b337f1525d76.jpg)
![yiiframework_3](https://cloud.githubusercontent.com/assets/4241620/11414857/57fc72a4-942d-11e5-849e-c65016d94e99.jpg)

I think current logo more modern with this font :)
What do you all opinion about 'framework' word gradation, this gradation with 70% Green and 30% Orange, any opinion or advice ? :)

@jacmoe I uploaded with 3 colors :)

**Comment by hscstudio** [comment]
@muhammadcahya 
I think it's very cool... 

Please comment to in https://github.com/yiisoft-contrib/yiiframework.com/issues/72
I propose new mockup.. maybe You have other briliant ide to mockup..

**Comment by jacmoe** [comment]
The font is Josefin Sans Regular?
I like the idea of using that.

However, that blue background would introduce yet another colour, which I don't like.
I do like the idea of applying a yellow to the word 'framework', though.
Perhaps Yii-yellow?

Unfortunately, only webkit-browsers supports gradients for text, but with a solid colour fall-back, it would work. :)

If you could make that logo in Inkscape, @muhammadcahya ?
I have uploaded the petals svg here: http://testing.jacmoe.dk/yii_petals.svg
Would be cool if you could insert matching text.

In my opinion should the logo be able to have different colours depending on context.
On dark backgrounds and on light backgrounds..

My idea is also to use a real font for the logos on the site, but that would not work for downloadable logos, of course, which is why we need a 'master logo'.
In svg, because you can generate any size from that, and because it is more universal than eps (I think).

I will make some screenshots of the site with Josefin Sans applied shortly.

**Comment by jacmoe** [comment]
Using Josefin Sans:
![yiilogo12](https://cloud.githubusercontent.com/assets/85424/11415637/cf91788c-9405-11e5-87fa-f2b843e74b3e.png)
![yiilogo13](https://cloud.githubusercontent.com/assets/85424/11415638/d4a20008-9405-11e5-844a-1a5f2257fb45.png)
I actually prefer the version with small letters - yiiframework..

Yellow did not look good ;(

But the font itself works nicely :)

**Comment by jacmoe** [comment]
I have made the body text Roboto which is a font that goes well with Josefin :)

I am all in favor of the Josefin font.

I am currently using a local webfont but perhaps we should use the Google font service?
The license of Josefin requires us to rename the fonts (since they are derivates..) but apparent not when Google is serving them..

**Comment by jacmoe** [comment]
One last screen shot - showing Josefin and Roboto in concert:
![yiilogo14](https://cloud.githubusercontent.com/assets/85424/11415868/937ee1c4-9408-11e5-8978-0adf28d4fed6.png)

**Comment by egorio** [comment]
@samdark, ![untitled-1](https://cloud.githubusercontent.com/assets/1502496/11418639/9366eee8-93d6-11e5-970e-eee16c39e60d.png), but i'm not a good painter :)

**Comment by muhammadcahya** [comment]
>If you could make **that logo **in Inkscape..

@jacmoe Are you mean my yii logo propose ?

I have uploaded the svg logo here [mynacreative.com/yiilogo_propose.svg](http://mynacreative.com/yiilogo_propose.svg)

---

@egorio I like your logo who @samdark chose, but I think if the logo has been representing the identity of one of the words (Yii), It was like forcing the next word should be 'framework' alone, so it would be *difficult* to use the full text 'Yii Framework', because 'Yii' words has been representing in logo. (My Opinion)

**Comment by hscstudio** [comment]
@muhammadcahya : please create mockup with your briliant logo.. :)

**Comment by hscstudio** [comment]
@muhammadcahya : I want You use this font for content.. https://www.google.com/fonts/specimen/Poiret+One
inspiring from this http://www.dhezign.com/

burn your creativity dude :)

**Comment by jacmoe** [comment]
My proposal for the new and updated Yii logo is this:
![yiilogo21](https://cloud.githubusercontent.com/assets/85424/11487985/5f39269a-97c3-11e5-9d3d-e28f2a3c7950.png)
![yiilogo22](https://cloud.githubusercontent.com/assets/85424/11487989/64b6a534-97c3-11e5-9341-d875940d57a8.png)
It is using Josefine Sans Regular for the font and #888 for the colour.

**Comment by jacmoe** [comment]
To see how it looks in context, I hereby repost my image from #72 here:
![yiilogo23](https://cloud.githubusercontent.com/assets/85424/11488029/aee2e898-97c3-11e5-877a-3c642248d668.png)

For a white background, 'yii' could be turned Yii-blue - I should probably do one using that - but I think I like the new look - it is modern and light, while still keeping that lovely Yii petal. ;)

**Comment by jacmoe** [comment]
I tried to make two "official" logos, and have to admit that I utterly suck at Inkscape..

![yii-logo-color svg](https://cloud.githubusercontent.com/assets/85424/11489246/fa30c66c-97cd-11e5-8f34-9fab1ee38dda.png)
![yii-logo-transparent svg](https://cloud.githubusercontent.com/assets/85424/11489248/fece15f8-97cd-11e5-979a-9c041538d43a.png)

I have uploaded the source svg files here:

[yii-logo-color.svg](http://testing.jacmoe.dk/yii-logo-color.svg)

[yii-logo-transparent.svg](http://testing.jacmoe.dk/yii-logo-transparent.svg)

**Comment by samdark** [comment]
1. Grey doesn't look good on dark-blue.
2. Blue part of the logo blends with background which isn't good.
3. The text is too close to the logo.

**Comment by jacmoe** [comment]
The colours - blue/grey - are the exact same as the live site. I guess they don't work well when taken out of context.

Maybe the blue logo could go altogether, leaving only two logos: transparent background and white background?

Or maybe only the one with transparent background?

The text can be moved, no problem.

**Comment by samdark** [comment]
About the colors I mean these do not work well when placed on exactly this background.

**Comment by jacmoe** [comment]
I hate that logo :p

![yiilogo25](https://cloud.githubusercontent.com/assets/85424/11499208/a91d94a6-9824-11e5-8beb-61b3503e7d90.png)
![yiilogo26](https://cloud.githubusercontent.com/assets/85424/11499217/b17a8f96-9824-11e5-9e8e-7f8e81c81a36.png)
![yiilogo27](https://cloud.githubusercontent.com/assets/85424/11499218/b69d11b0-9824-11e5-8c58-b835612f177b.png)

If that is not acceptable, there is no choice but to remove all blue and go for a design like @hscstudio or @eshill

**Comment by samdark** [comment]
Well, yeah. Its blue is a "pefect" match with background. @hscstudio variant of the gradient is better in this regard.

**Comment by muhammadcahya** [comment]
@jacmoe can you try "YiiFramework" an show up to us
I think should be better :)

**Comment by jacmoe** [comment]
The Philosopher font - first post - looks much better capitalized than Josefine font.

It just breaks the angle of attack, if you get my meaning, from the logo and through the text.

**Comment by jacmoe** [comment]
See how it looks capitalized - I posted screenies of that earlier: https://github.com/yiisoft-contrib/yiiframework.com/issues/61#issuecomment-159808924

**Comment by samdark** [comment]
@jacmoe at that screenshot it looks bad because of space.

**Comment by jacmoe** [comment]
It looks bad regardless of spacing, IMO. :)

Our current logo also uses lower case because of the way the petals baseline aligns with the lowercase y and the lowercase f.
![yiilogo29](https://cloud.githubusercontent.com/assets/85424/11509324/c058a762-985d-11e5-93b5-538a0ea2d11a.png)
![yiilogo30](https://cloud.githubusercontent.com/assets/85424/11509325/c43a4192-985d-11e5-8877-21d8c6f30cd8.png)

**Comment by jacmoe** [comment]
![yiilogo31](https://cloud.githubusercontent.com/assets/85424/11509627/6601d89a-985f-11e5-8387-e958888c2c52.png)

Well, you are probably going to say that it looks really awesome :p

**Comment by samdark** [comment]
It is... okay :)

**Comment by samdark** [comment]
Padding could be added in CSS>

**Comment by jacmoe** [comment]
Using the transparent one, indeed. :)

**Comment by jacmoe** [comment]
That was easy enough - just export the page instead of the drawing:
![yii-logo-color svg](https://cloud.githubusercontent.com/assets/85424/11510301/5dea0ba6-9863-11e5-9510-e8ceabf69fc1.png)

**Comment by jacmoe** [comment]
We are not going to provide a black/white version, are we?

**Comment by jacmoe** [comment]
I propose that we offer png's and svg's for download.

**Comment by jacmoe** [comment]
I exported the logo - blue version with transparent background - and this is the result:
![yiilogo32](https://cloud.githubusercontent.com/assets/85424/11510759/a6ac8682-9865-11e5-909f-fbc30717d327.png)

Only problem now is that I need to show a different image on mobile, but that is minor..

Also, we should probably provide a transparent version download option for the blue as well..

**Comment by cebe** [comment]
looks really nice to me!

**Comment by jacmoe** [comment]
That is a relief :)

I think that we can get away with two versions: one for light backgrounds (blue yii) and one for dark backgrounds (white yii) - both with transparent backgrounds. Because, who makes logos with solid color background these days anyway?

**Comment by samdark** [comment]
Noone :)

**Comment by andydodot** [comment]
![logo-yii](https://cloud.githubusercontent.com/assets/11666599/11539711/27849f60-995b-11e5-8303-d32b514886f4.png)

Hello,I just try to give a fresh new look at the typeface.
I use font coolvetica (yii) and stark (framework).

Gradation of black circles mean a totality of features incorporated from the fast, secure and professional.

Thanks.
Andy Dodot

**Comment by jacmoe** [comment]
I really appreciate what you are trying to do Andy, but the logos are already made :)

Of course, things can change, but until they do, I consider this issue solved.

About your logos: the 'Stark' font works well, but Coolvetica is awful! I can see what your thinking was, but that font is not an improvement over the 'old' logo font, in my opinion.

But thanks for putting in an effort :)

I will close this issue, for now. Thanks.
