### ISSUE TITLE
Centering content ui

### ISSUE THREAD

**Issue by Arhell** [yiisoft-contrib/yiiframework.com#628]
![1](https://user-images.githubusercontent.com/26163841/94656746-211bef80-0309-11eb-9530-8efc10c396cd.jpg)
https://www.yiiframework.com/download

**Comment by samdark** [comment]
What is the issue? How do you want to adjust it?

**Comment by Arhell** [comment]
Сenter the text with the code block

**Comment by samdark** [comment]
That will make it less readable. I'd not do it.

**Comment by Arhell** [comment]
got it ok
