### ISSUE TITLE
There will be no YiiCamp in the launch version

### ISSUE THREAD

**Issue by cebe** [yiisoft-contrib/yiiframework.com#66]
There are the following things which need to be taken from the old site and integrated in the new one:

- [x] adjust navigation
- [ ] port the wiki
- [ ] port extensions
- [ ] port the user management

**Comment by samdark** [comment]
What do you mean by "adjust navigation"?

**Comment by cebe** [comment]
current nav contains "camp" and also links there for tutorials, extensions etc.

**Comment by samdark** [comment]
Ah,

**Comment by cebe** [comment]
closing, tasks are covered in different issues.
