### ISSUE TITLE
Ads?

### ISSUE THREAD

**Issue by jacmoe** [yiisoft-contrib/yiiframework.com#79]
Should I leave empty spots for ads in my design of the site?

If the ads are going to be in, then it would be better if I reserved spots for them rather than trying to retro-fit them to the design afterwards.

I wish that Yii could use Carbon rather than Google ads, but maybe Yii is not elite enough. :)

And, if ads are in, what pages will carry ads?

**Comment by qiangxue** [comment]
Nope. We will not put ads on the new site (only place having ads could be the forum, but that's TBD).

**Comment by jacmoe** [comment]
Excellent!
Thanks @qiangxue - the site will be classier without them.
