### ISSUE TITLE
icon font does not work on mobile

### ISSUE THREAD

**Issue by cebe** [yiisoft-contrib/yiiframework.com#82]
![screenshot_2015-12-06-22-55-13](https://cloud.githubusercontent.com/assets/189796/11616013/f2456ad8-9c6f-11e5-9d93-9ceb22784df6.png)
![screenshot_2015-12-06-22-56-00](https://cloud.githubusercontent.com/assets/189796/11616008/e86243d8-9c6f-11e5-896b-416ba6a6b7dc.png)

firefox mobile 42.0.1

**Comment by samdark** [comment]
@cebe can you briefly check http://www.stay.com/ to get an idea if it's general FF mobile issue or just implementation?

**Comment by cebe** [comment]
![screenshot_2015-12-07-01-09-37](https://cloud.githubusercontent.com/assets/189796/11616591/45be01d4-9c7f-11e5-96f1-de18425a6c00.png)

**Comment by jacmoe** [comment]
Will see to hooking my mobile up with my machine to see if I can reproduce.

**Comment by samdark** [comment]
So it's implementation, not general issue. At Stay.com we're using icon fonts as well.

**Comment by jacmoe** [comment]
It does not work on desktop either - just did a fresh clone and build (due to repository change) - and I got weird characters.

**Comment by jacmoe** [comment]
Could you try this again, please?

After running `gulp fonts`

**Comment by cebe** [comment]
fixed, thanks!
