### ISSUE TITLE
make search box visible

### ISSUE THREAD

**Issue by cebe** [yiisoft-contrib/yiiframework.com#83]
@jacmoe I think the search box should stay as it was before to be always visible. Imo it is a core feature of the site so one can directly type class names and search api docs. It may also be autofocused so you can directly go typing. At least on the start page there is no other element that would need focus.

**Comment by jacmoe** [comment]
It is always visible?
When you click the eyeglas icon the dropdown flies out and you can search
without leaving the page.
It looks like crap when the form is inlined and there is no need to do it
IMO.
The second version is in the mobile collapse.

**Comment by cebe** [comment]
I mean that the input field should be directly visible and may also directly have focus.

**Comment by jacmoe** [comment]
Maybe we could arrange a compromise so that there be a search bar under the
navbar for API and Guide pages?

**Comment by cebe** [comment]
why not in the nav bar? we have a lot of space there.

**Comment by cebe** [comment]
It also should not be limited to the guide and api pages because when I enter the main page I'd directly want to start searching the docs.

**Comment by jacmoe** [comment]
Because it looks and feels awful.
The form does not play well with it,and if there is a static search bar for
guide and API pages there is no need to ruin the classy navbar that we
currently have.
A static and floating search bar will be a better solution, I think.

**Comment by jacmoe** [comment]
I can give the spyglass dropdown a keyboard shortcut?
Den 07/12/2015 00.27 skrev "Carsten Brandt" <notifications@github.com>:

**Comment by jacmoe** [comment]
Maybe I could float a search box in the blue jumbo, next to the gh ribbon?
Win-win?!

**Comment by cebe** [comment]
> Because it looks and feels awful.

please explain why. 

> I can give the spyglass dropdown a keyboard shortcut?

keyboard shortcut does not really help, most people would not know it works.

> Maybe I could float a search box in the blue jumbo, next to the gh ribbon?

not sure, need to see it, imo something like this looks totally fine:

![searchbar](https://cloud.githubusercontent.com/assets/189796/11616438/605ca792-9c7b-11e5-9eea-a28daec37f45.png)

**Comment by jacmoe** [comment]
I will put it there. ;)

**Comment by jacmoe** [comment]
![searchblue](https://cloud.githubusercontent.com/assets/85424/11640750/87a7bae4-9d34-11e5-8b9b-4a3ebd549055.jpg)

Satisfied? :P

**Comment by cebe** [comment]
completely, thanks! :)

**Comment by jacmoe** [comment]
It now is autofocused - at least for modern browsers:
http://www.w3schools.com/tags/att_input_autofocus.asp
