### ISSUE TITLE
update yii3 link

### ISSUE THREAD

**Issue by Arhell** [yiisoft-contrib/yiiframework.com#861]
remove underline

**Comment by samdark** [comment]
Why? It was added on purpose.

**Comment by Arhell** [comment]
1. Remove underline on hover
![20-08-2021 13-18-05](https://user-images.githubusercontent.com/26163841/130219127-34e20564-e63e-4347-b0ee-12e848555814.jpg)

2. fix on mobile 

![20-08-2021 13-19-05](https://user-images.githubusercontent.com/26163841/130219194-17e4c09e-af06-469f-ba69-2a30f8b42158.jpg)
