### ISSUE TITLE
Make a versions info page

### ISSUE THREAD

**Issue by cebe** [yiisoft-contrib/yiiframework.com#89]
like http://php.net/supported-versions.php

**Comment by jacmoe** [comment]
Excellent idea :+1:

**Comment by jacmoe** [comment]
https://github.com/php/web-php/blob/master/supported-versions.php

https://github.com/php/web-php/blob/master/images/supported-versions.php

**Comment by samdark** [comment]
https://www.yiiframework.com/release-cycle
