### ISSUE TITLE
Search in Extensions returns way too many results

### ISSUE THREAD

**Issue by juppwerner** [yiisoft-contrib/yiiframework.com#890]
I put "openapi" into the search box while on the Extensions page (https://www.yiiframework.com/extensions), then press ENTER.

I get 1,120 results, which do look all the same.

**Comment by Deele** [comment]
Confirmed, just searched "captcha" and first 23 pages consists of the same extension.

https://www.yiiframework.com/search?version=2.0&type=extension&q=captcha&page=23

Probably related to invalid SQL query performed [during search](https://github.com/yiisoft-contrib/yiiframework.com/blob/5e1bb62c6eb4a537854ae7062d228f8fd15d933a/models/search/SearchActiveRecord.php) and could be a simple join issue and needs result grouping by ID added.

**Comment by arogachev** [comment]
Closing as duplicate of #664.
