### ISSUE TITLE
Github SSO authentication error

### ISSUE THREAD

**Issue by letsjump** [yiisoft-contrib/yiiframework.com#892]
I'm getting an error while trying a github SSO login to my yiiframework.com account.

**Comment by samdark** [comment]
Reproduced with my account as well. Thanks for reporting.

**Comment by samdark** [comment]
Looks like nasty bots are indexing the website too much so we've reached limits on multiple services. Need to ban em and wait a bit.

**Comment by samdark** [comment]
Fixed.
