### ISSUE TITLE
Fix the layout (mobile styles)

### ISSUE THREAD

**Issue by Altenrion** [yiisoft-contrib/yiiframework.com#91]
There are some troubles in css of the layout. 

If you would test the adaptivity of the screen ,  resizing from 1049 px  width and less, you would see, that if you will try to slide page to the left, the whole site would move on some pixels. On mobile (like nexus 5) it is all 50px of white space on the right  side of the site! Some one suggested  that this is because of the "up the page" button. But i suppose that this is because of the broken html. I had same issue a year ago. My problem was solved by closing one or two the tags in layout.

**Comment by jacmoe** [comment]
What page?

**Comment by cebe** [comment]
![screenshot_2015-12-14-03-12-52](https://cloud.githubusercontent.com/assets/189796/11771457/d0dde20c-a210-11e5-8c70-3687319d694d.png)

**Comment by jacmoe** [comment]
I removed some invalid markup so maybe it works better now?

**Comment by jacmoe** [comment]
Scrap that: I see it now :p

**Comment by jacmoe** [comment]
Feel free to reopen if this issue is not fixed for you :)

**Comment by cebe** [comment]
fixed, thanks.
