### ISSUE TITLE
Top menu

### ISSUE THREAD

**Issue by samdark** [yiisoft-contrib/yiiframework.com#93]
Currently top menu consists of several dropdowns. It's not perfect usability-wise.

- New users should have catchy things they need right at the front page.
    - Getting started should probably be in place of download button since primary way is to install via Composer anyway.
- Exising users need API, Guide and Forum all the time. Other things not so often.

**Comment by samdark** [comment]
I propose to have a single line menu:

```
Guide | API | Forum | Wiki | Extensions | More...
```

More is a dropdown that would contain everything else.

**Comment by jacmoe** [comment]
Good idea because the new theme does not have the topbar.
You can assign me and I will change it as the first thing when I start
implementation of the eshill theme ;)

**Comment by rob006** [comment]
I think we should have single line menu with dropdowns.

* Documentation
  * Get started
  * Guide
  * API
  * Wiki
  * Books
  * ...
* Resources
  * Extensions
  * Releases/Download ?
  * News ?
  * ...
* Community
  * Forum
  * Chat
  * GitHub
  * ...
* About
  * other stuff...

**Comment by samdark** [comment]
You mean multiple dropdowns? That won't allow quick one-click access to most used things such as API, Guide and Forum.

**Comment by rob006** [comment]
We can use hover effect for devices with mouse to toggle dropdowns. Then mouse click on Documentation, Resources and Community can move directly to Guide, Extensions or Forum. Only touch devices will require two clicks.

**Comment by samdark** [comment]
Personally I hate dropdowns that are opened on hover even more than regular dropdowns. These are just annoying...

**Comment by cebe** [comment]
I agree that direct access is better than dropdown, but we have just too many items to put in there...

**Comment by rob006** [comment]
Do you really think so advanced users will use Guide or API links in menu? I guess so they just use search and go directly to page what they looking for.

**Comment by samdark** [comment]
See it here: https://github.com/yiisoft-contrib/yiiframework.com/issues/94

**Comment by jacmoe** [comment]
Why are we having this discussion **again**?

In my mock, I was told to put menu entries in drop downs, and later on we agreed that it should not fly out automatically.
And then it was decided to put guide and api links in a topbar because they really should be there.
...

Now I think we have gone full circle. :+1: 

In this stage I am doing nothing that deviates a single iota from what @eshill has in his mockup.

We have gone through just about every permutation of what a navbar could look like ;p

**Comment by samdark** [comment]
That's good to experience it :)
