### ISSUE TITLE
Rebranding - again

### ISSUE THREAD

**Issue by jacmoe** [yiisoft-contrib/yiiframework.com#95]
When we did the rebranding in #61 we wanted to have the old petal.

However, because of the new theme, we can't have the old tri-coloured petal, so I made new logos:
![yiiguide4](https://cloud.githubusercontent.com/assets/85424/11828948/34202e0e-a399-11e5-8c59-16577a84c41e.jpg)

I also have a third Yii petal in greyscale - should we have a greyscale logo additionally?

**Comment by jacmoe** [comment]
I have used PT sans and Eshill Blue and updated the svg's.

I am not sure about the favicon - perhaps light petal on Eshill Blue ?

**Comment by jacmoe** [comment]
![android-icon-96x96](https://cloud.githubusercontent.com/assets/85424/11829163/dea48932-a39a-11e5-9d2b-0d408715a691.png)

**Comment by jacmoe** [comment]
![yii_petals-dark](https://cloud.githubusercontent.com/assets/85424/11829174/f3563b3c-a39a-11e5-84e2-327e83efc362.png)

**Comment by jacmoe** [comment]
I have updated the favicons to use the second petal - the dark version.

**Comment by jacmoe** [comment]
And then it looks like this:
![yiiguide5](https://cloud.githubusercontent.com/assets/85424/11829413/ad38bb82-a39c-11e5-9c8d-c34a3669da7a.jpg)

**Comment by cebe** [comment]
> However, because of the new theme, we can't have the old tri-coloured petal

why is that?

**Comment by jacmoe** [comment]
Because @eshill is the boss :)

**Comment by jacmoe** [comment]
We can keep it as a mascot, like a third possible icon, and available on it's own.

It is easier to integrate into a theme if the petals are monochromatic.

So, I vote that we keep the old and add two new ones.

The real problem is that the Eshill Blue colour clashes violently with the blue in the Yii petal and makes it look out of place.
It does not look professional.

Let's keep them all :+1:

**Comment by jacmoe** [comment]
The colourful logo for light backgrounds:
![logo-colour-light-base](https://cloud.githubusercontent.com/assets/85424/11830064/e9d6f61c-a3a1-11e5-85b5-6d233a7c10d8.png)

**Comment by jacmoe** [comment]
The colourful logo for dark backgrounds:
![logo-colour-base](https://cloud.githubusercontent.com/assets/85424/11830127/67a6d454-a3a2-11e5-9f9e-f90549d5f84f.png)

**Comment by jacmoe** [comment]
And, finally:
![logo-colour-grey-base](https://cloud.githubusercontent.com/assets/85424/11830266/93264532-a3a3-11e5-895a-3e5229f5d9cd.png)

**Comment by jacmoe** [comment]
Now, the logo page looks like this:
![yiiguide6](https://cloud.githubusercontent.com/assets/85424/11830678/9caec9d6-a3a7-11e5-890e-ffec62149d70.jpg)

**Comment by cebe** [comment]
> Because @eshill is the boss :)

seems I missed some communication somewhere... where is the new layout and when did we decide to use it? :)

**Comment by jacmoe** [comment]
In the #72 topic and in #94 - where this page was made obsolete by new logos from Sergei.

**Comment by jacmoe** [comment]
https://cloud.githubusercontent.com/assets/47294/11420550/e31d662e-943f-11e5-9e6f-1aba72b706a1.png

https://cloud.githubusercontent.com/assets/47294/11818359/02139302-a36b-11e5-8ce7-6e21f2463797.png

**Comment by cebe** [comment]
yeah had not seen these, thanks!
