### ISSUE TITLE
API buttons

### ISSUE THREAD

**Issue by samdark** [yiisoft-contrib/yiiframework.com#96]
Near each method there are the following buttons:

![API buttons](https://cloud.githubusercontent.com/assets/47294/11874154/4c192b6c-a4ef-11e5-998b-508162adfdd2.png)

They aren't really clear and are looking messy.

**Comment by samdark** [comment]
Options are:

1. Replace these w/ text: `View | Edit | Direct link`.
2. Somehow change the visual representation so there are not that many visual elements and it's more obvious what each one does. @eshill is gonna try doing it.

**Comment by samdark** [comment]
In the current guide these are better.

![Current guide](https://cloud.githubusercontent.com/assets/47294/11874264/cdc2bda4-a4ef-11e5-996d-816e3d7d550a.png)

**Comment by samdark** [comment]
Still I think the meaning of each one could be represented better.

**Comment by samdark** [comment]
Or not :) Seems either we need to get rid of these extra icons after eye and pencil or change all these into text.

**Comment by jacmoe** [comment]
I can remove the external link style, for now, and see if there is an
elegant way of only applying it to actual links. Maybe a class
*"linkalize"*?

**Comment by cebe** [comment]
scroll up is not needed, direct link could be added to the headline instead so it is consistent with the guide.

**Comment by cebe** [comment]
@jacmoe maybe the external link style could be limited to some scope like `.guide-content a` ?

**Comment by cebe** [comment]
or generally limit it to links inside of paragraphs: `p a`.

**Comment by samdark** [comment]
I'm for applying it to content only.

**Comment by jacmoe** [comment]
It is actually applied to content only :)
I changed it to 'content p a'.

**Comment by samdark** [comment]
How about the following?

```html
<ul>
    <li><a ...>external</a></li>
</ul>
```

**Comment by jacmoe** [comment]
That totally defeats the purpose :)

**Comment by samdark** [comment]
Another way is to add a CSS rule that hides these markers for API links only.
