### ISSUE TITLE
Books section

### ISSUE THREAD

**Issue by samdark** [yiisoft-contrib/yiiframework.com#99]
http://yiiframework.domain-na.me/books is very cool but pretty much unusable. Scrolling into tiny box and finding a link inside of it is a pain.

**Comment by jacmoe** [comment]
Should they go, or should they be in 3 columns on big screen and one on small screens?
The intention was to save space.
I could make them flip over instead?

**Comment by jacmoe** [comment]
On mobile they should collapse into one column and be big enough..

**Comment by samdark** [comment]
There's no need to save space on a big screen, I think.

**Comment by samdark** [comment]
Haven't checked how it works on devices.

**Comment by samdark** [comment]
Checked on mobile. Animation is slugish but overall it works well.

**Comment by rob006** [comment]
Why not show a single book per row with a visible description?

**Comment by jacmoe** [comment]
Because me goal was to create something a bit more memorable than just 10 rows of books :)

I can change it to that. It is just not especially entertaining. I know that the primary goal is not to entertain but inform, but it does not have to look like a wikipedia page either.

Any ideas to make it better? :)

**Comment by jacmoe** [comment]
Packt does something like it: https://www.packtpub.com/all

Perhaps we could simpliply and put the description of each book in a modal?

**Comment by jacmoe** [comment]
That should give us an interesting gallery of books with neat touches and people can easily view each book in a modal, even on mobile devices (without any tedious scrolling)

**Comment by samdark** [comment]
Modals isn't good idea if you can do w/o them in general.

**Comment by rob006** [comment]
Also 5 books it is a poor material for the gallery...

**Comment by jacmoe** [comment]
There are 10 books so far.

Alright. Good old boring old rows of books it is then :+1:

**Comment by rob006** [comment]
You need to split books per Yii version, so there will be 2 galleries with 5 books.

**Comment by jacmoe** [comment]
Robert: http://local.yiiframework.com/books

That is why I am not too keen on having that row of books on the front page.
IMO, it should be an random cover that links to the books page.
Otherwise it would be duplicate content, I think.
And that space could be used for better things.

I leave that to you to decide.

**Comment by jacmoe** [comment]
How about making a thumbnail carousel with the books instead?
Then people can click back and forth between the books by clicking their cover and get a detail view?
No modals and still neat.

**Comment by rob006** [comment]
> Robert: http://local.yiiframework.com/books

I can't see this.

**Comment by jacmoe** [comment]
Try this: http://yiiframework.domain-na.me/books

**Comment by jacmoe** [comment]
Okay, picture (pun intended) that those black boxes are thumbnails of the 5 books and what you can see above it is the detail view of the active book:
![books1](https://cloud.githubusercontent.com/assets/85424/11912642/530d42e2-a647-11e5-95f9-89ba9ded5657.jpg)
That is going to make the page interesting and compact and still highly readable. Thoughts?

**Comment by rob006** [comment]
How this will work on mobile?

**Comment by jacmoe** [comment]
It can be swiped or clicked.

**Comment by jacmoe** [comment]
Would be based on [unslider](http://unslider.com/) I think because it is tiny and looks better than Bootstrap's carousel.
Also planning to use that for the top of the index - the tour section - and for the testimonials.
It needs to work on any device, of course.

**Comment by rob006** [comment]
But there will be no space for carousel and detailed description on screen, so user needs to click cover, scroll to detailed description, read, back to carousel, click another cover, scroll to description.... and so on. Not very practical...

**Comment by jacmoe** [comment]
No :)
Check out this gallery: http://johnpolacek.github.io/ResponsiveThumbnailGallery/
The idea is that once you click the image, the page is shown. It is like tabbed interface, except that the tabs are the images.
In fact, I could probably just use a tab container, come to think of it. No sliding with that, but it will also work.

**Comment by rob006** [comment]
![72195389df7e812f9250bd70ad24](https://cloud.githubusercontent.com/assets/5972388/11912791/c2fa7ba0-a64d-11e5-821f-947de0795969.png)

**Comment by jacmoe** [comment]
I decided to just make it a regular one book per row page :)
Because, for some reason, Bootstrap guys did not make the media object reponsive, it probably needs a separate partial for small devices. I can do that.

**Comment by jacmoe** [comment]
I typed while you posted @rob006 - what is that image?

**Comment by jacmoe** [comment]
This is a quick initial go at the list page:
![books2](https://cloud.githubusercontent.com/assets/85424/11912795/2f2d27aa-a64e-11e5-9cb3-16fac099091e.jpg)

It does need some additional styling, like padding and background etc. But it is not too bad, although ordinary.
That should give us time to think about this.

**Comment by jacmoe** [comment]
OK, done redoing:
![books3](https://cloud.githubusercontent.com/assets/85424/11912995/d4ce7b3a-a655-11e5-807f-897846cad091.jpg)

**Comment by jacmoe** [comment]
By the way, @eshill will probably change everything :p

But a question for Sergei:
The front page, the books section - I was thinking if we could shrink that down to a randomly selected book cover that links to the dedicated books page?
And use the link overlay effect like on http://coffeecodeandcats.com/ ?
The link overlay could be styled to fit with the site - light green dashed style.
I think that it would help keep the front page clean. What do you think?

**Comment by eshill** [comment]
@jacmoe I will design a section of books.
Now, I think we need to concentrate on the Essentials - Guide & API

**Comment by samdark** [comment]
Top 4 books from Yii 2 config file are now displayed at front page.

**Comment by eshill** [comment]
I planned on index 5 books
![2016-01-04 11-44-23 index png](https://cloud.githubusercontent.com/assets/11502920/12086190/bbd21814-b2d8-11e5-9a8e-2f3490ddb274.png)

**Comment by jacmoe** [comment]
How am I supposed to fit 5 columns into 12 columns?

**Comment by eshill** [comment]
Manually. without bootstrap grid :)

**Comment by samdark** [comment]
I'll handle that.

**Comment by eshill** [comment]
@samdark wizard

**Comment by samdark** [comment]
Done.

**Comment by eshill** [comment]
corrections on index page:
![books-sections-edit](https://cloud.githubusercontent.com/assets/11502920/12216473/e471e690-b6f3-11e5-8f84-a897cf8c55b6.jpg)

Books page:
![books](https://cloud.githubusercontent.com/assets/11502920/12216478/fb20e418-b6f3-11e5-98da-5b20c1c51314.png)

**Comment by eshill** [comment]
![books](https://cloud.githubusercontent.com/assets/11502920/12220783/0359137e-b791-11e5-9560-fb101d18d40c.png)

**Comment by eshill** [comment]
today is not like the illustration with 2 books :-(
I'll try to do better.

**Comment by eshill** [comment]
@samdark it's better?

![books](https://cloud.githubusercontent.com/assets/11502920/12234254/b5b8532c-b87c-11e5-9ef3-988a047fda4e.png)

[books.svg.zip](https://github.com/yiisoft-contrib/yiiframework.com/files/85750/books.svg.zip)

**Comment by samdark** [comment]
Much better!

**Comment by jacmoe** [comment]
The second books is much, much better - it is great ! :+1:

**Comment by eshill** [comment]
@samdark @jacmoe Thanks!

**Comment by samdark** [comment]
Updated books section with new layout.

**Comment by jacmoe** [comment]
:+1:

**Comment by cebe** [comment]
can this be closed? as far as I see it is done.

**Comment by cebe** [comment]
please reopen if not.
